---
title: "Analysis of NPS/AD"
subtitle: 'STAR-solo R1-4 merged h5ad: complete bulk'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{Decorrelate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---


<!--- 

cd /hpc/users/hoffmg01/work/nps_ad
ml python
R
# rm -rf analysis_2_cache/ /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/sceCombine_v2.RDS

system("ml git; git pull")
rmarkdown::render("analysis_2_complete_bulk.Rmd");


# https://hoffmg01.u.hpc.mssm.edu/nps_ad/


ml git
cd ~/build2/dreamlet
git pull
R CMD INSTALL .


--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r load.packages, cache=FALSE}
# Use cache=FALSE so that package are fully loaded each time
# This ensures that forks within mclapply() have these loaded
# Othewise, mclapply() not have access to these libraries and will fail 
#   unless the libraries are manually loaded within each fork
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(HDF5Array)
library(dreamlet)
library(muscat)
library(cowplot)
library(zenith)
library(scater)
library(data.table)
library(S4Vectors)
library(tidyverse)
library(kableExtra)
library(qvalue)
library(GSEABase)
})

# packageVersion("zellkonverter") >= 1.3.1
# https://github.com/theislab/zellkonverter

```


```{r load.data, cache=FALSE}
datafile = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/sceCombine_v2.RDS"

if( file.exists(datafile) ){
  # reading data from RDS is much faster:
  #   especially good for pipeline development
  sceCombine = readRDS( datafile )
}else{
  # read snRNA-seq data with annotations build in
  h5ad_file = "/sc/arion/projects/CommonMind/leed62/NPS-AD/analysis_solo/NPS-AD_roundMerged_pass2_anno.h5ad"
  sceCombine = readH5AD(h5ad_file, X_name = "counts", target="raw/X", use_hdf5=TRUE)

  # set metadata to empty to reduce size and speep up development time
  metadata(sceCombine) = list()

  saveRDS(sceCombine, file=datafile)
}
```

Data freeze includes 4 rounds, `r length(table(sceCombine$batch))` batches, `r length(table(sceCombine$SubID))` donors, and `r format(ncol(sceCombine), big.mark=',')` cells passing QC.


```{r combineData, message=TRUE}
# Specify how to collapse into pseudo-bulk
sceCombine$id <- paste0(sceCombine$batch, '_', sceCombine$SubID)
sceCombine$CompleteBulk = "One"

sceCombine_prep <- prepSCE(sceCombine, 
    kid = "CompleteBulk", # subpopulation assignments
    gid = "SubID",  # group IDs (i.e. Donor)
    sid = "id",   # sample IDs (i.e. Batch_Donor)
    drop = TRUE)

# Create pseudo-bulk SingleCellExperiment
pbObj <- aggregateToPseudoBulk(sceCombine_prep,
    assay = "counts", 
    fun = "sum",
    by = c("cluster_id", "sample_id"),
    BPPARAM = SnowParam(12, progressbar=TRUE))

# Combine with phenotype data at the Donor level
# read metadata
meta_file = "/sc/arion/projects/CommonMind/leed62/NPS-AD/MSSM_HBCC_RUSH_clinical_metadata_combo.csv"
df_meta = fread(meta_file)
df_meta = df_meta[,-1]

# save original order of samples
colData(pbObj)$row.order = 1:nrow(colData(pbObj))

# merge colData with additional metadata
df_merge = merge(colData(pbObj), df_meta, by.x= "group_id", by.y="SubID", all.x=TRUE)

# set rownames to be same as original, based on row.order
# These rownames determine colnames(pbObj), which is used downstream
rownames(df_merge) = rownames(colData(pbObj))[df_merge$row.order]

# extract batch info per sample
df_batching = with( colData(sceCombine), unique(data.frame(id, round_num, batch, prep, HTO)))
df_merge = merge(df_merge, df_batching, by.x= "row.names", by.y="id", all.x=TRUE)

rownames(df_merge) = df_merge$Row.names
df_merge = df_merge[,-1]

# save merged data as colData while retaining original cell order
colData(pbObj) = df_merge[order(df_merge$row.order),]
colData(pbObj)$row.order = c()# remove row.order

# Set levels for Dx2
lvls = sort(unique(as.character(colData(pbObj)$Dx2)))
lvls = lvls[-which(lvls=="Control")]
colData(pbObj)$Dx2 = factor(colData(pbObj)$Dx2, c("Control", lvls))

saveRDS(pbObj, file="/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/pbObj_v2_complete_bulk.RDS" )

pbObj
```

```{r cell.type.comp}
library(compositions)

# compute cell type composition using ilr

# read standard pseudobulk
pb = readRDS("/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/pbObj_v2.RDS")
countMatrix = do.call(rbind, int_colData(pb)$n_cells)
df_ctc = ilr(countMatrix)
colnames(df_ctc) = paste0("ctc_", 1:ncol(df_ctc))

df = merge(colData(pbObj), df_ctc, by="row.names")
rownames(df) = df$Row.names
df = df[,-1]
colData(pbObj) = df[rownames(colData(pbObj)),]
```


```{r voom}
# Normalize and apply voom
res.proc = processAssays( pbObj, ~ (1|group_id) + (1|batch) + (1|round_num) + (1|HTO), 
  min.cells = 5,
  min.count = 10, 
  # pmetadata = df_collapse,  
  # pkeys=c('ID', 'anno'),
  BPPARAM = SnowParam(16, progressbar=TRUE))
  
res.proc
```

```{r voom.plot, fig.height=6, fig.width=6, cache=TRUE}
plotVoom( res.proc )
```


```{r plot.sex, eval=FALSE}
 
library(org.Hs.eg.db)

# find genes on chrX
# df_gene = select(org.Hs.eg.db, keys=rowData(sceCombine)$gene_id, keytype="ENSEMBL", columns=c("SYMBOL", "CHR"))
# df_gene_chrx = df_gene[with(df_gene, CHR=="X" & !is.na(CHR)),]

# res = DelayedArray::rowSums(assay(sceCombine, "counts")[df_gene_chrx$ENSEMBL,1:10000])


df_gene = select(org.Hs.eg.db, keys=c("IL1RAPL1", "UTY"), keytype="SYMBOL", columns="ENSEMBL")

df_sex = lapply( names(res.proc), function(CT){
  geneExpr = res.proc[[CT]]
  df = NULL
  if( sum(df_gene$ENSEMBL %in% rownames(geneExpr)) == 2){  
    df = data.frame(cellType = CT, IDS = colnames(geneExpr$E), IL1RAPL1 = geneExpr$E[df_gene$ENSEMBL[1],], UTY = geneExpr$E[df_gene$ENSEMBL[2],])
  }
  df
})
df_sex = do.call(rbind, df_sex)

df_sex = merge(df_sex, colData(pbObj)[,"Sex",drop=FALSE], by.x="IDS", by.y="row.names")

ggplot(as.data.frame(df_sex), aes(IL1RAPL1, UTY, color=Sex)) + geom_point() + theme_classic() + facet_wrap(~cellType)
```



```{r varPart.plain}
form = ~ (1|group_id)

res.vp = fitVarPart(res.proc, form, BPPARAM = SnowParam(18, progressbar=TRUE))
```

```{r vp.plot.plain, fig.height=6, fig.width=6, cache=FALSE}
colnames(res.vp) = gsub("scale\\.", "", colnames(res.vp))
colnames(res.vp) = gsub("\\.", "", colnames(res.vp))
colnames(res.vp) = gsub("group_id", "Donor", colnames(res.vp))
plotVarPart( sortCols(res.vp) )
```

```{r varPart}
form = ~ (1|group_id) + (1|batch) + (1|round_num) + (1|HTO) + (1|Dx2) + (1|Sex) + scale(Age) + scale(PMI)

res.vp = fitVarPart(res.proc, form, BPPARAM = SnowParam(18, progressbar=TRUE))
```

```{r vp.plot, fig.height=6, fig.width=6, cache=TRUE}
colnames(res.vp) = gsub("scale\\.", "", colnames(res.vp))
colnames(res.vp) = gsub("\\.", "", colnames(res.vp))
colnames(res.vp) = gsub("group_id", "Donor", colnames(res.vp))
plotVarPart( sortCols(res.vp) )
```


```{r varPart.ctc}
form = ~ (1|group_id) + (1|batch) + (1|round_num) + (1|HTO) + (1|Dx2) + (1|Sex) + scale(Age) + scale(PMI)
form = paste0('~', as.character(form)[2], ' + ', paste(colnames(df_ctc), collapse=" + "))
form = as.formula(form)

res.vp.ctc = fitVarPart(res.proc, form, BPPARAM = SnowParam(18, progressbar=TRUE))

# aggregate cell type composition
res.vp.ctc2 = as.data.frame(res.vp.ctc[,-c(1,2)])
res.vp.ctc2$CTC = rowSums(res.vp.ctc2[,colnames(df_ctc)])
res.vp.ctc2 = res.vp.ctc2[,! colnames(res.vp.ctc2) %in% colnames(df_ctc)]
```

```{r vp.plot.ctc, fig.height=6, fig.width=6, cache=TRUE}
colnames(res.vp.ctc2) = gsub("scale\\.", "", colnames(res.vp.ctc2))
colnames(res.vp.ctc2) = gsub("\\.", "", colnames(res.vp.ctc2))
colnames(res.vp.ctc2) = gsub("group_id", "Donor", colnames(res.vp.ctc2))
plotVarPart( sortCols(res.vp.ctc2) )
```



# Correlation with and between donors
```{r within_btw, fig.height=6, fig.width=6}
source("/sc/arion/work/hoffmg01/nps_ad/common_analyses.R")

eval_within_across_donor( res.proc )
```


```{r dreamlet.fit}
form = ~ Sex + (1|group_id) + (1|batch) + (1|round_num) + (1|HTO) + Dx2 + scale(Age) + scale(PMI)

fit.dl = dreamlet( res.proc, form, BPPARAM=SnowParam(36))
```

```{r de.summary}
coefs = c('Dx2AD', 'Dx2BP', 'Dx2SCZ')

tabLst = lapply( coefs, function(key){
  tab = topTable(fit.dl, coef=key, number=Inf)

  tab %>% 
    as_tibble %>% 
    group_by(assay) %>% 
    summarise( coef = key, 
      nGenes = length(adj.P.Val), 
      nDE = sum(adj.P.Val < 0.05),
      pi1 = 1 - qvalue(P.Value)$pi0)
  })
tab = do.call(rbind, tabLst)

as.data.frame(tab)
```

```{r de.plots}
ggplot(tab, aes(assay, nGenes, fill=assay)) + geom_bar(stat="identity") + facet_wrap(~coef) + theme_classic() + theme(aspect.ratio=1, legend.position="none", axis.text.x = element_text(angle = 45, vjust=1, hjust=1) )

ggplot(tab, aes(assay, nDE, fill=assay)) + geom_bar(stat="identity") + facet_wrap(~coef) + theme_classic() + theme(aspect.ratio=1, legend.position="none", axis.text.x = element_text(angle = 45, vjust=1, hjust=1) )

ggplot(tab, aes(assay, pi1, fill=assay)) + geom_bar(stat="identity") + facet_wrap(~coef) + theme_classic() + theme(aspect.ratio=1, legend.position="none", axis.text.x = element_text(angle = 45, vjust=1, hjust=1) )
```

# Volcanos
```{r volcanos.1, fig.width=6, fig.height=6}
plotVolcano( fit.dl, coef = coefs[1] ) + ggtitle(coefs[1])
```

```{r volcanos.2, fig.width=6, fig.height=6}
plotVolcano( fit.dl, coef = coefs[2] ) + ggtitle(coefs[2])
```

```{r volcanos.3, fig.width=6, fig.height=6}
plotVolcano( fit.dl, coef = coefs[3] ) + ggtitle(coefs[3])
```



# zenith for gene set analysis
```{r zenith}
# Load Gene Ontology database 
go.gs = get_GeneOntology()

ngenes = sapply(go.gs, function(gs) length(geneIds(gs)))
go.gs = go.gs[(ngenes > 20) & (ngenes < 2000)]

coefs = c('Dx2AD', 'Dx2BP', 'Dx2SCZ')

res.gsa = lapply( coefs, function(key){

  # check inter.gene.cor=NA
  zenith_gsa(fit.dl, coefs=key, go.gs, inter.gene.cor=.01)
})
names(res.gsa) = coefs
res.gsa_cat = do.call(rbind, res.gsa)
```

```{r zenith.heatmap.1, fig.width=6, fig.height=6}
fig = plotZenithResults(res.gsa[[1]], 5, 2) + ggtitle(names(res.gsa)[1])
```

```{r zenith.heatmap.2, fig.width=6, fig.height=6}
fig = plotZenithResults(res.gsa[[2]], 5, 2) + ggtitle(names(res.gsa)[2])
```

```{r zenith.heatmap.3, fig.width=6, fig.height=6}
fig = plotZenithResults(res.gsa[[3]], 5, 2) + ggtitle(names(res.gsa)[3])
```



# MDS from pseudobulk
```{r pseudobulk.MDS}
library(edgeR)
library(Rfast)

pb = readRDS("/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/pbObj_v2.RDS")
pb2 = readRDS("/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/pbObj_v2_complete_bulk.RDS")

pb.flat = pbFlatten(pb)
geneExpr = assay(pb.flat, "counts")

geneExpr2 = assay(pb2, "One")
colnames(geneExpr2) = paste0(colnames(geneExpr2), ".Bulk")

geneExpr_merge = merge(geneExpr, geneExpr2, by="row.names")
rownames(geneExpr_merge) = geneExpr_merge$Row.names
geneCounts = geneExpr_merge[,-1]

dge = DGEList( geneCounts )
dge = calcNormFactors( dge )
geneExpr = cpm(dge, log=TRUE)

C = 1 - cora(t(scale(t(geneExpr))))

df_cmd = cmdscale( C )
df_cmd = as.data.frame(df_cmd)
df_cmd$CellType = sapply(strsplit(colnames(geneExpr), "\\."), function(x) x[2])

ggplot(df_cmd, aes(V1, V2, color=CellType)) + geom_point() + theme_classic() + theme(aspect.ratio=1) + xlab("Coordinate 1") + ylab("Coordinate 2") + ggtitle("MDS of pseudobulk")
```



```{r exit2, cache=FALSE, eval=TRUE, echo=FALSE}
knitr::knit_exit()
```









