---
title: "Analysis of NPS/AD"
subtitle: 'STAR-solo R1-4 merged h5ad'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{Decorrelate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---


<!--- 

cd /hpc/users/hoffmg01/work/nps_ad
ml python
R
# rm -rf analysis_2_cache/

system("ml git; git pull")
rmarkdown::render("analysis_2.Rmd");


# https://hoffmg01.u.hpc.mssm.edu/nps_ad/


ml git
cd ~/build2/dreamlet
git pull
R CMD INSTALL .


--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r load.packages, cache=FALSE}
# Use cache=FALSE so that package are fully loaded each time
# This ensures that forks within mclapply() have these loaded
# Othewise, mclapply() not have access to these libraries and will fail 
#   unless the libraries are manually loaded within each fork
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(HDF5Array)
library(dreamlet)
library(muscat)
library(cowplot)
library(zenith)
library(scater)
library(data.table)
library(S4Vectors)
})

# packageVersion("zellkonverter") >= 1.3.1
# https://github.com/theislab/zellkonverter

```


```{r load.data, cache=FALSE}
datafile = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/sceCombine_v2.RDS"

if( file.exists(datafile) ){
  # reading data from RDS is much faster:
  #   especially good for pipeline development
  sceCombine = readRDS( datafile )
}else{
  # read snRNA-seq data with annotations build in
  h5ad_file = "/sc/arion/projects/CommonMind/leed62/NPS-AD/analysis_solo/NPS-AD_roundMerged_pass2_anno.h5ad"
  sceCombine = readH5AD(h5ad_file, "counts", use_hdf5=TRUE)

  # set metadata to empty to reduce size and speep up development time
  metadata(sceCombine) = list()

  saveRDS(sceCombine, file=datafile)
}
```

Data freeze includes 4 rounds, `r length(table(sceCombine$batch))` batches, `r length(table(sceCombine$SubID))` donors, and `r format(ncol(sceCombine), big.mark=',')` cells passing QC.

# Joint UMAP
```{r umap, dev="png"}
# extract UMAP coordinates and annotations
df = cbind(reducedDim(sceCombine, "X_umap"), colData(sceCombine)[,c("anno", "celltype", "class", "subtype", "leiden_labels")])
df = data.frame(df)

ggplot(df, aes(V1, V2, color=anno)) + geom_point(size=.05) + theme_classic() + theme(aspect.ratio=1) + guides(colour = guide_legend(override.aes = list(size = 1.5))) + xlab("UMAP1") + ylab("UMAP2")
```

```{r umap2, dev="png"}
ggplot(df, aes(V1, V2, color=celltype)) + geom_point(size=.05) + theme_classic() + theme(aspect.ratio=1) + guides(colour = guide_legend(override.aes = list(size = 1.5))) + xlab("UMAP1") + ylab("UMAP2")
```

```{r umap3, dev="png"}
ggplot(df, aes(V1, V2, color=class)) + geom_point(size=.05) + theme_classic() + theme(aspect.ratio=1) + guides(colour = guide_legend(override.aes = list(size = 1.5))) + xlab("UMAP1") + ylab("UMAP2")
```

```{r umap4, dev="png"}
ggplot(df, aes(V1, V2, color=subtype)) + geom_point(size=.05) + theme_classic() + theme(aspect.ratio=1) + guides(colour = guide_legend(override.aes = list(size = 1.5))) + xlab("UMAP1") + ylab("UMAP2")
```

```{r umap5, dev="png"}
ggplot(df, aes(V1, V2, color=leiden_labels)) + geom_point(size=.05) + theme_classic() + theme(aspect.ratio=1) + guides(colour = guide_legend(override.aes = list(size = 1.5))) + xlab("UMAP1") + ylab("UMAP2")
```


```{r combineData}
# Specify how to collapse into pseudo-bulk
sceCombine$id <- paste0(sceCombine$batch, '_', sceCombine$SubID)
sceCombine_prep <- prepSCE(sceCombine, 
    kid = "celltype", # subpopulation assignments
    gid = "SubID",  # group IDs (i.e. Donor)
    sid = "id",   # sample IDs (i.e. Batch_Donor)
    drop = TRUE)

# Create pseudo-bulk SingleCellExperiment
pbObj <- aggregateToPseudoBulk(sceCombine_prep,
    assay = "counts", 
    fun = "sum",
    by = c("cluster_id", "sample_id"),
    BPPARAM = SnowParam(12, progressbar=TRUE))

# Combine with phenotype data at the Donor level
# read metadata
meta_file = "/sc/arion/projects/CommonMind/leed62/NPS-AD/MSSM_HBCC_RUSH_clinical_metadata_combo.csv"
df_meta = fread(meta_file)
df_meta = df_meta[,-1]

# save original order of samples
colData(pbObj)$row.order = 1:nrow(colData(pbObj))

# merge colData with additional metadata
df_merge = merge(colData(pbObj), df_meta, by.x= "group_id", by.y="SubID", all.x=TRUE)

# set rownames to be same as original, based on row.order
# These rownames determine colnames(pbObj), which is used downstream
rownames(df_merge) = rownames(colData(pbObj))[df_merge$row.order]

# extract batch info per sample
df_batching = with( colData(sceCombine), unique(data.frame(id, round_num, batch, prep, HTO)))
df_merge = merge(df_merge, df_batching, by.x= "row.names", by.y="id", all.x=TRUE)

rownames(df_merge) = df_merge$Row.names
df_merge = df_merge[,-1]

# save merged data as colData while retaining original cell order
colData(pbObj) = df_merge[order(df_merge$row.order),]
colData(pbObj)$row.order = c()# remove row.order

saveRDS(pbObj, file="/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/pbObj_v2.RDS" )

pbObj
```


```{r voom}
# Normalize and apply voom
res.proc = processAssays( pbObj, ~ (1|group_id) + (1|batch) + (1|round_num) + (1|HTO), 
  min.cells = 5,
  min.count = 10, 
  # pmetadata = df_collapse,  
  # pkeys=c('ID', 'anno'),
  BPPARAM = SnowParam(16, progressbar=TRUE))
  
res.proc
```

```{r voom.plot, fig.height=10, fig.width=10, cache=TRUE}
plotVoom( res.proc )
```


```{r plot.sex}

df_sex = lapply( names(res.proc), function(CT){
  geneExpr = res.proc[[CT]]
  df = NULL
  if( sum(c("XIST", "UTY") %in% rownames(geneExpr)) == 2){  
    df = data.frame(cellType = CT, IDS = colnames(geneExpr$E), XIST = geneExpr$E["XIST",], UTY = geneExpr$E["UTY",])
  }
  df
})
df_sex = do.call(rbind, df_sex)
df_sex = data.table(df_sex)

fig = ggplot(df_sex, aes(XIST, UTY)) + geom_point() + theme_classic() + facet_wrap(~cellType)

ggsave(file="test.pdf", fig)




```


```{r dreamlet.fit}
form = ~ Sex + (1|group_id) + (1|batch) + (1|round_num) + (1|HTO) + (1|Dx2) + Age + PMI + pH

fit.dl = dreamlet( res.proc, form, BPPARAM=SnowParam(36))

saveRDS( fit.dl, "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/fit.dl.RDS")
```




```{r varPart}
form = ~ (1|group_id) + (1|batch) + (1|round_num) + (1|HTO) + (1|Dx2) + Age + (1|Sex) + PMI + pH

res.vp = fitVarPart(res.proc, form, BPPARAM = SnowParam(18, progressbar=TRUE))
```

```{r vp.plot, fig.height=15, fig.width=10, cache=FALSE}
plotVarPart( sortCols(res.vp) )
```


### Examine variancePartition results
```{r vp.examine, fig.height=2, fig.width=7}
CT = "Astrocyte"

i = 1:3
df = sortCols(res.vp)[res.vp$assay == CT,]
rownames(df) = df$gene
i = c(i, which.max(df$Donor), which.max(df$Batch), which.max(df$Residuals))

plotPercentBars( data.frame(df[i,-c(1,2)])) + ggtitle(CT)
```

Examples

```{r vp.examine2, fig.height=6, fig.width=8, cache=TRUE}      
figList = lapply( df$gene[i], function(geneName){
  df = merge( as.data.frame(t(assay(res.proc, CT)$E[geneName,,drop=FALSE])), colData(res.proc), by="row.names")

  plotStratifyBy(df, 'group_id', geneName, colorBy=NULL, main=geneName) + theme(aspect.ratio=1)
})
plot_grid( plotlist=figList, nrow=2 )
```



# Correlation with and between donors
```{r within_btw, fig.height=10, fig.width=10}
source("/sc/arion/work/hoffmg01/nps_ad/common_analyses.R")

eval_within_across_donor( res.proc )
```









```{r exit1, cache=FALSE, eval=TRUE}
knitr::knit_exit()
```











