---
title: "Analysis template for RUSH"
subtitle: 'Public Release 0'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
---



<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/template/
ml python git pandoc
git pull origin master
R --vanilla

system("git pull origin master"); rmarkdown::render("dreamlet_template.Rmd");

# https://hoffmg01.hpc.mssm.edu/nps_ad/nps_ad/analysis/freeze2/template/dreamlet_template.html

--->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load libraries
```{r load.packages, cache=FALSE}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(zellkonverter)
library(dreamlet)
library(zenith)
library(DelayedArray)
library(GSEABase)
library(scater)
library(tidyverse)
library(scattermore)
})

# update block size for reading h5ad file from disk
setAutoBlockSize(1e9)
```

# Load data
```{r load.data}
file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/RUSH_2023-02-07_14_21.h5ad" 
sce = readH5AD(file, use_hdf5=TRUE, verbose=TRUE)
assayNames(sce)[1] = "counts"

# order of cell types used for plotting
# also ensures cell types have consistent colors
ctorder = c('EN_L2_3_IT', 'EN_L3_5_IT_1', 'EN_L3_5_IT_2', 'EN_L3_5_IT_3', 'EN_L5_IT', 'EN_L5_6_NP', 'EN_L6_CT', 'EN_L6_IT', 'EN_NF', 'IN_ADARB2', 'IN_LAMP5', 'IN_PVALB', 'IN_PVALB_CHC', 'IN_SST', 'IN_VIP', 'Oligo', 'OPC', 'Astro', 'Micro_PVM', 'CD8_T', 'PC', 'VLMC','Endo', "Immune")
```

# Summarizing data
## UMAP
```{r umap3}
plotProjection(sce, "X_umap", "subclass", order=ctorder)  + ggtitle("subclass")
```


# Compute pseudobulk 
```{r combineData, message=TRUE}
# Create pseudo-bulk SingleCellExperiment
pb = aggregateToPseudoBulk(sce[1:100, 1:10000],
  assay = "counts", 
  cluster_id = "subclass",
  sample_id = "Channel",
  BPPARAM = SnowParam(1))
```


# Process data: log2 CPM + voom precision weights
```{r voom}
# Normalize and apply voom
# form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age) + (1|Dx)
form = ~ 1

res.proc = processAssays( pb, form, BPPARAM = SnowParam(12))
```


```{r voom.plot, fig.height=15, fig.width=10, cache=TRUE}
plotVoom( res.proc, ncol=4, assays=ctorder ) + theme_classic()  
```


# Variance Partitioning Analysis
```{r varPart}
form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age) + AD

res.vp = fitVarPart(res.proc, form, BPPARAM = SnowParam(12))
```


# Differential expression: dreamlet analysis
```{r dreamlet}
# form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age) + AD
form = ~ AD

fit = dreamlet( res.proc, form, BPPARAM = SnowParam(12))
```

## Volcano
```{r volcano, fig.height=15, fig.width=10}
plotVolcano(fit, "AD1", ncol=4, assays=ctorder) + theme_classic()
```



## Gene set analysis
```{r zenith}
# Load Gene Ontology database 
go.gs = get_GeneOntology(to="SYMBOL")

# remove set with > 1000 genes
go.gs = go.gs[sapply(go.gs, function(x) length(geneIds(x))) < 1000]

# zenith analysis 
res.gsa = zenith_gsa(fit, go.gs, coefs="AD1")
```

```{r zenith.heatmap.1, fig.width=10, fig.height=25, cache=FALSE} 
# remove "GO0022625: " from gene set name
res.gsa$Geneset = gsub("^GO\\S+ ", "", res.gsa$Geneset)
res.gsa$assay = factor(res.gsa$assay, ctorder)  

plotZenithResults(res.gsa, 10, 3) + theme(legend.position="bottom") 
```