---
title: "Examine technical variables"
subtitle: 'Identify variables to include as covariates'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  DATASET: NULL
---


<!--- 


cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/covariates/
ml python git pandoc gcc/11.2.0
git pull origin master
R --vanilla --no-restore



system("git pull origin master"); rmarkdown::render("examine_covariates.Rmd")



# https://hoffmg01.hpc.mssm.edu/nps_ad/analysis/freeze2/covariates/examine_covariates.html

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r load.packages, cache=FALSE}
library(synapser)
library(tidyverse)
library(matrixStats)
library(ggplot2)
library(RColorBrewer)
library(pheatmap)

synLogin()
```

```{r analysis}
# Read gene expression files
# Perform PCA
folder = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/residuals/"
files = dir(folder, pattern = ".*2023-09.*_residualsPearson_SubID_class_.*.tsv.gz", full.names=TRUE)

pcaList = lapply(files, function(file){

  df_expr = read.table(file, header=TRUE, row.names=1)

  dcmp = prcomp(t(df_expr))

  CT = gsub(".*_(\\S+).tsv.gz", "\\1", basename(file))
  cohort = gsub("^(\\S+)_20.*$", "\\1", basename(file))
  tibble(data.frame(ID = rownames(dcmp$x), class = CT, cohort = cohort, dcmp$x[, 1:5]))
  })

cohorts = gsub("^(\\S+)_20.*$", "\\1", basename(files))
pcids = c("PC1", "PC2", "PC3", "PC4", "PC5")

df_pca = lapply(unique(cohorts), function(chrt){

  i = which(chrt == cohorts)

  do.call(rbind, pcaList[i]) %>%
      select(!one_of('cohort')) %>%
      pivot_wider(names_from = c("class"), 
      values_from = pcids)
  }) 
names(df_pca) = unique(cohorts)
```

```{r downstream, cache=FALSE}
# Read metadata files
df_cov_wet = read_tsv(synGet("syn51375322")$path)
df_cov_dry = read_tsv(synGet("syn51276625")$path, skip=2)

# donor list
donorList = strsplit(df_cov_dry$EXPECTED_DONORS, " ")
donors = unique(unlist(donorList))

# numeric columns
cols =  df_cov_dry %>% 
    summarise_all(class) %>% 
    gather(col_name, col_type) %>%
    filter(col_type == "numeric") %>%
    pull(col_name)

# extact mean value per donor
df = lapply(donors, function(id){

  # which row
  i = which(sapply(donorList, function(x) id %in% x))

  df_cov_dry[i,cols] %>%
    colMeans %>%
    data.frame %>%
    t() %>%
    data.frame(ID = id, .)
})
df = do.call(rbind, df) %>% as_tibble
```

```{r merge, cache=FALSE}
df_res = lapply(names(df_pca), function(cohort){

  df_merge = df %>%
        inner_join(df_pca[[cohort]], by="ID")

  cv = colVars(as.matrix(df_merge[,-1]), na.rm=TRUE)
  exclude = c("ID", names(cv)[cv==0])

  C = df_merge %>%
    select(-one_of(exclude)) %>%
    cor(use="pairwise.complete")

  include = grep("^PC\\d_", rownames(C))

  res = C[-include, include]

  colnames(res) = paste(cohort, colnames(res), sep=": ")
  res
})
df_res = do.call(cbind, df_res)
colnames(df_res) = gsub("_2023-09-12", "", colnames(df_res))
```

```{r cor, cache=FALSE, fig.height=15, fig.width=15}
ncols = 50
fcol = colorRampPalette(c("blue", "white", "red"))(ncols)

pheatmap(df_res, 
  breaks = seq(-1, 1, length.out=ncols+1),
  color = fcol,
  fontsize = 6,
  cellheight = 5,
  cellwidth=5, 
  cluster_cols=TRUE)
```

```{r cor.abs, cache=FALSE, fig.height=15, fig.width=15}
ncols = 50
fcol = colorRampPalette(c("white", "red"))(ncols)
pheatmap(abs(df_res), 
  breaks = seq(0, 1, length.out=ncols+1),
  color = fcol,
  fontsize = 6,
  cellheight = 5,
  cellwidth=5, 
  cluster_cols=TRUE)
```

# Sum across cell types
```{r sums, fig.width=6, fig.height=15}
library(ggplot2)

df_rs = data.frame(name = rownames(df_res), 
  corMean = rowMeans(abs(df_res)))

ggplot(df_rs, aes(corMean, name)) +
  geom_bar(stat="identity") +
  theme_classic() +
  theme(aspect.ratio=2)
```





# Correlation between covariates
```{r cca, fig.height=15, eval=FALSE}
library(dreamlet)

path = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/"

h5ad_files = c(
RUSH = "RUSH_2023-09-12_16_13.h5ad", 
HBCC = "HBCC_2023-09-12_16_28.h5ad",
MSSM = "MSSM_2023-09-12_17_04.h5ad",
FULL = "FULL_2023-09-12_18_32.h5ad",
AGING = "AGING_2023-09-12_20_35.h5ad")

h5ad_files = sapply(h5ad_files, function(x) paste0(path, x))

sample_id = "SubID"
cluster_id = "class"
pbList = lapply( names(h5ad_files[-4]), function(id){

  params = list(DATASET = h5ad_files[id])

  filePrefix = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/", gsub(".h5ad$", "", basename(params$DATASET)), "_PB_", sample_id, "_", cluster_id)
  file = paste0(filePrefix, ".RDS")
  readRDS(file)
})
names(pbList) = names(h5ad_files[-4])

# formula
form = ~ Sex + scale(Age) + scale(PMI) + (1|mod_BRAAK_AD) + mod_Plq_Mn + (1|mod_CERAD) + (1|mod_CDRScore) + mod_Cognitive_Resilience + (1|MajorDisease) + (1|DementiaType) + log(n_genes) 

# make figures
figList = lapply( names(pbList), function(id){

  message(id)

  pb.mod = pbList[[id]]

  i = (all.vars(form) %in% colnames(colData(pb.mod))) 
  vars.keep = all.vars(form)[i]

  j = apply(colData(pb.mod)[,vars.keep,drop=FALSE], 2, function(x) length(unique(x)) > 1)
  vars.keep = vars.keep[j]

  form2 = paste("~", paste(vars.keep , collapse=" + "))

  C = canCorPairs(form2, colData(pb.mod))

  rownames(C) = gsub("mod_", "", rownames(C))
  colnames(C) = gsub("mod_", "", colnames(C))

  plotCorrMatrix(C, main=id)
})
```




