---
title: "Analysis of NPS/AD"
subtitle: 'Compositional anaysis: freeze 1'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{Decorrelate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze_v1
ml python git
git pull
# rm -rf analysis_freeze1_cache/ analysis_freeze1_files
R --vanilla

system("git pull")
rmarkdown::render("analysis_freeze1.Rmd");


# https://hoffmg01.u.hpc.mssm.edu/nps_ad/


echo "echo \"rmarkdown::render('analysis_freeze1.Rmd');\" | R" > script.sh


bsub -Is -q interactive -R "span[hosts=1]" -W 12:00 -P acc_CommonMind -n 24 bash



ml git
cd ~/build2/dreamlet
git pull
R CMD INSTALL .

npsad:roussoslab

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r load.packages, cache=FALSE}
library(crumblr)
```


```{r load.data}
file = paste0(outfolder, 'cellCounts.RDS')
df_cellCounts = readRDS(file)

file = paste0(outfolder, 'colData.RDS')
info = readRDS(file)
```








# Cell type composition

## Plot cell type composition
```{r plotCellComposition, fig.height=20, fig.width=5, eval=FALSE}
tab = sort(table(pbObj$dx))
tab = tab[tab>40]

figLst = lapply(names(tab), function(lvl){

  idx = which(pbObj$dx == lvl)
  idx = idx[!is.na(idx)]

  fig = plotCellComposition(pbObj[,idx]) + ggtitle(lvl) 

  if( lvl != names(tab)[which.max(tab)] ){
    fig = fig + theme(legend.position="none")
  }
  fig
})
plot_grid(plotlist=figLst, rel_heights= tab, ncol=1, align="hv", axis="tblr")
```


```{r plotCellComposition.summary, fig.height=4, fig.width=6}
df_cellCount = do.call(rbind, int_colData(pbObj)$n_cells)

plotCellComposition( t(colSums(df_cellCount)))
```




## Partition variation in cell type composition
```{r cellTypeCompositionVarPart, fig.height=4, fig.width=6}
# Add dream here
# deal with NA's here 
form = ~ (1|SubID) + (1|batch) + (1|round_num) + (1|HTO) + (1|Sex) + (1|dx) + (1|Institution) + scale(Age) 

i = with(as.data.frame(colData(pbObj)), !is.na(dx) & !is.na(Age) & !is.na(Sex))

library(crumblr)

# crumblr transform cell counts
cobj = crumblr(cellCounts(pbObj[,i]))

# variance partitioning analysis
df_vp = fitExtractVarPartModel(cobj, form, as.data.frame(colData(pbObj[,i])))

# rownames(df_vp) = df_vp$assay
colnames(df_vp) = gsub("scale\\.", "", colnames(df_vp))
colnames(df_vp) = gsub("\\.", "", colnames(df_vp))
colnames(df_vp) = gsub("SubID", "Donor", colnames(df_vp))

plotPercentBars( df_vp )
```

```{r vst, fig.width=7, fig.height=7}
# compute cell fractions
fractions = t(apply(cellCounts(pbObj[,i]), 1, function(x){
  x = x+1
  x / sum(x)
}))

# correlation between cell types
plotCorrMatrix( cor(t(vst(cobj))) )
```

```{r pca}
# PCA on VST
res = prcomp( t(vst(cobj)), scale.=FALSE )

# merge with subject metadata
df_pca = merge(as.data.frame(res$x), colData(pbObj[,i]), by="row.names")
df_pca = merge(df_pca, fractions, by.x="Row.names", by.y="row.names")

df_pca %>%
      ggplot(aes(PC1, PC2, color=dx)) + 
        geom_point() +
        theme_classic() +
        theme(aspect.ratio=1, legend.position="right")

df = cor(df_pca[,2:3], df_pca[,c( 'Age', colnames(fractions))], method="sp")
df = data.frame(variable = colnames(df), t(df))

df %>%
  pivot_longer(cols=-"variable", names_to="PC") %>%
  ggplot(aes(PC, variable, fill=value)) +
      geom_tile() +
      theme_classic() +
      theme(aspect.ratio=5) +
      scale_fill_gradient2(name = "Correlation", low="blue", mid="white", high="red", limits=c(-1, 1))
```

## Perform statistical tests
For each cell type


```{r cellTypeCompositionTest}
form = ~ (1|SubID) + (1|batch) + (1|round_num) + (1|HTO) + (1|Sex) + (1|Institution) + dx + scale(Age) 

fit = dream(cobj, form, as.data.frame(colData(pbObj[,i])))
fit = eBayes(fit)

topTable(fit, coef=coefs[1], number=Inf, sort.by="none")[,1:5] %>% 
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[1]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")

topTable(fit, coef=coefs[2], number=Inf, sort.by="none")[,1:5] %>%
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[2]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")

topTable(fit, coef=coefs[3], number=Inf, sort.by="none")[,1:5] %>% 
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[3]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")
```


Examine effect of batch.  Check composition with age.

```{r test.composiution}
form = ~ (1|SubID)  + (1|batch)  + (1|round_num) + (1|HTO) + (1|Institution) + dx*Sex + scale(Age) 

i = with(as.data.frame(colData(pbObj)), (dx %in% c("AD", "Control")) & !is.na(Age) & !is.na(Sex))

# crumblr transform cell counts
cobj = crumblr(cellCounts(pbObj))


fit = dream(cobj[,i], form, as.data.frame(colData(pbObj[,i])))
fit = eBayes(fit)

head(coef(fit))

topTable(fit, coef='dxAD', number=Inf, sort.by="none")
```



```{r test.composiution.plots}

# library(crumblr)
form = ~ (1|SubID) + (1|batch)  + (1|round_num) + (1|HTO) + (1|Institution) + Sex + scale(Age) 

i = with(as.data.frame(colData(pbObj)), (dx %in% c("Control")) & !is.na(Age) & !is.na(Sex))

# crumblr transform cell counts
cobj = crumblr(cellCounts(pbObj))


fractions = t(apply(cellCounts(pbObj), 1, function(x){
  x = x+1
  x / sum(x)
}))


fit = dream(cobj[,i], form, as.data.frame(colData(pbObj[,i])))
fit = eBayes(fit)

head(coef(fit))

topTable(fit, coef='scale(Age)', number=Inf, sort.by="none")

# fractions[i,]
# t(cobj[,i]$E)

merge(colData(pbObj)[i,], fractions[i,], by="row.names") %>% 
  as_tibble %>% 
  group_by(SubID) %>% 
  summarize(OPC = mean(OPC),
    Age = Age[1]) %>%
  ggplot(aes(Age, OPC)) + 
    geom_point() + 
    theme_classic() + 
    theme(aspect.ratio=1) + 
    geom_smooth(method="lm")

# ggsave("test.png", fig)


x = as.data.frame(fractions[i,][order(colData(pbObj)$Age[i]),])

tail(x)

plotPercentBars( x ) + theme(axis.text.y=element_blank())

# ggsave("test.png", fig)


merge(colData(pbObj)[i,], fractions[i,], by="row.names") %>% 
  as_tibble  %>% 
  mutate(ord = factor(Row.names[order(Age)])) %>% 
  pivot_longer(cols=colnames(fractions), values_to="frac", names_to="CellComp") %>%ggplot(aes(ord, y=frac, fill=CellComp)) +
    geom_bar(position="stack", stat="identity")  + 
    theme(axis.text.x=element_blank())

# ggsave("test.png", fig)

library(propr)

res = propr( cellCounts(pbObj) + .5, metric="rho" )

# png("test.png")
plotCorrMatrix(res@matrix)
# dev.off()

source("helper/flow.R")

from = c(t(x[1,]))
names(from) = colnames(x)

to = c(t(x[492,]))
names(to) = colnames(x)

D.rate = getTransitionAverages(from, to)



# Plots of data and inferred rates
plotFromToBars(from, to) + coord_flip()

# ggsave("test.png", fig)

plotFromToMatrix(D.rate) + theme(axis.text.x=element_text(angle=45, hjust=1))

# ggsave("test.png", fig)

# png("test.png")
plotFromToNetwork( D.rate )
 dev.off()
```

```{r remaCor, eval=FALSE}
tab = topTable(fit, coef=coefs[1], number=Inf, sort.by="none")
tab = tab[grep("neuron", rownames(tab)),]

library(remaCor)

se = with(tab, logFC/t)
C =  cor(t(vst(cobj)))
i = grep("neuron", rownames(C))

C[i,i]

LS( tab$logFC, se, cor=C[i,i])

RE2C( tab$logFC, se, cor=C[i,i])
```




### Collapse neuronal subtypes
```{r cellTypeCompositionVarPart.neuron, fig.height=4, fig.width=6}
# Add dream here
# deal with NA's here 
form = ~ (1|SubID) + (1|batch) + (1|round_num) + (1|HTO) + (1|Sex) + (1|dx) + (1|Institution) + scale(Age) 

i = with(colData(pbObj), !is.na(dx) & !is.na(Age) & !is.na(Sex))

df_counts = as.data.frame(cellCounts(pbObj[,i]))
idx = grep("GABA|Gluta", colnames(df_counts))

# include summed neurons
df_counts$Neurons = rowSums(df_counts[,idx])

# drop split neurons
df_counts = df_counts[,-idx]

cobj = crumblr(as.matrix(df_counts))
df_vp = fitExtractVarPartModel(cobj, form, as.data.frame(colData(pbObj[,i])))

# rownames(df_vp) = df_vp$assay
colnames(df_vp) = gsub("scale\\.", "", colnames(df_vp))
colnames(df_vp) = gsub("\\.", "", colnames(df_vp))
colnames(df_vp) = gsub("SubID", "Donor", colnames(df_vp))

plotPercentBars( df_vp )
```

## Perform statistical tests
For each cell type
```{r cellTypeCompositionTest.neuron}
form = ~ (1|SubID) + (1|batch) + (1|round_num) + (1|HTO) + (1|Sex) + (1|Institution) + dx + scale(Age) 

fit = dream(cobj, form, as.data.frame(colData(pbObj[,i])))
fit = eBayes(fit)

topTable(fit, coef=coefs[1], number=Inf, sort.by="none")[,1:5] %>% 
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[1]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")

topTable(fit, coef=coefs[2], number=Inf, sort.by="none")[,1:5] %>%
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[2]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")

topTable(fit, coef=coefs[3], number=Inf, sort.by="none")[,1:5] %>% 
  kable(digits=c(2, 2, 2, 3, 3, 2, 2), caption=coefs[3]) %>% 
  kable_classic(full_width = FALSE, html_font = "Cambria")
```


