---
title: 'secoia'
subtitle: '<u>S</u>ingl<u>e</u> <u>C</u>ell <u>O</u>utlier <u>I</u>dentification <u>A</u>nalysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{secoia}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---


<!---


cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze_v1
ml python git
git pull

R
system("git pull"); rmarkdown::render("secoia.Rmd")

# rm -rf secoia_cache/ secoia_files/

https://hoffmg01.u.hpc.mssm.edu/nps_ad/freeze_v1/secoia.html


--->


<style>
body {
text-align: justify}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r packages, cache=FALSE}
library(scater)
library(secoia)
library(BiocParallel)
library(SingleCellExperiment)
library(dplyr)
library(PRROC)
```

```{r load}
outfolder = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze1.5_results/"

# sceCombine = readRDS( datafile )

# # aggregate genes on chromosomes
# sceAggr = aggregateAcrossFeatures(sceCombine, rowData(sceCombine)$gene_chrom)
 
# saveRDS(sceAggr, paste0(outfolder, "/sceAggr.RDS"))

sceAggr = readRDS(paste0(outfolder, "/sceAggr.RDS"))
```

```{r run.model}
# formula = ~ (1|SubID) + (1|batch)
formula = ~ 1

res = secoia(sceAggr, "celltype", formula, 
          BPPARAM = SnowParam(12, progressbar=TRUE), 
          includeVariables = c("AD", "Sex", "SubID", "Age", "Channel", "batch"))
```



```{r plot.res}
table(res$result$fdr_down < 0.05)
table(res$result$fdr_up < 0.05)
 
qqplot(res)
```

```{r plotPercentBars, eval=FALSE}
plotPercentBars(res)
``` 

```{r plot_resid_pred}
plotResidPred(res)
```

```{r plot_effect_size}
plotEffectSize(res)
```

```{r predict.sex}
status = c("Sex", "Male", "Female")
# status = c("AD", 0, 1)

getpref = function(df, status){
  idx1 = df[[status[1]]] == status[2]
  idx2 = df[[status[1]]] == status[3]

  idx1 = idx1[!is.na(idx1)]
  idx2 = idx2[!is.na(idx2)]

  pr = pr.curve(df$residuals[idx1], 
                df$residuals[idx2], 
                rand=TRUE)

  data.frame(AUPR = pr$auc.integral, 
            AUPR.rand=pr$rand$auc.integral)
}

df_aupr = res$results %>%
  group_by(celltype, chrom) %>%
  summarize(getpref(.data,status))

ggplot(df_aupr, aes(celltype, AUPR, fill=celltype)) +
  geom_bar(stat="identity") +
  geom_point(aes(celltype, AUPR.rand)) + 
  theme_classic() +
  theme(aspect.ratio=1, legend.position="none", plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(limits=c(0,1), expand=c(0,0)) +
  coord_flip() +
  ggtitle(paste("Classify", status[2])) +
  facet_wrap(~chrom)
# ggsave('~/www/test.pdf', fig, height=8, width=9)

res$results %>%
  filter(chrom=='Y') %>%
    ggplot(aes(celltype, residuals, fill=Sex)) +
    geom_violin() + 
  theme_classic() +
  coord_flip() +
  theme(aspect.ratio=1, legend.position="none", plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual("Sex", values=c("red", "blue"))
```

<!---
outfolder = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze1.5_results/"
datafile = paste0(outfolder, 'sceCombine_f1.5.RDS')
sceCombine = readRDS( datafile )


incl = sceAggr$celltype %in% c("Astrocyte", 'GABAergic neuron')
res = secoia(sceAggr[,incl], "celltype", 
          BPPARAM = SnowParam(12, progressbar=TRUE),
          includeVariables = c("AD", "Sex", "SubID"),
          method = "cpm")
--->



```{r plot.res2}
res2 = fitEmpiricalNull(res)
 
table(res2$result$fdr_down < 0.05)
table(res2$result$fdr_up < 0.05)

qqplot(res2)
```


```{r plot.res3}
# learn null only from AD controls
include = (res$results$AD == 0)
res3 = fitEmpiricalNull(res, include)
 
table(res3$result$fdr_down < 0.05)
table(res3$result$fdr_up < 0.05)
```

```{r qqplot3}
qqplot(res3)
```

```{r qqplot.grid, fig.width=12, fig.height=20}
qqplot(res3, facet_by = ~ chrom + celltype, 10, legend.position="none") + facet_grid( chrom ~ celltype ) 
```

```{r plot.res4, eval=FALSE}
# learn null only from AD controls
include = (res$results$AD == 0)
res4 = fitEmpiricalNull(res, include, jointNull=FALSE)
 
table(res4$result$fdr_down < 0.05)
table(res4$result$fdr_up < 0.05)
```

```{r qqplot.grid4, fig.width=12, fig.height=20, eval=FALSE}
qqplot(res4, facet_by = ~ chrom + celltype, 10, legend.position="none") + facet_grid( chrom ~ celltype ) 
```

```{r eval.mean.resids, eval=FALSE}

# Transformation scores 
res3$results$z.loss = -pmin(res3$results$residuals, 0)
res3$results$z.gain = pmax(res3$results$residuals, 0)

table(res3$results$fdr_up < 0.05)
table(res3$results$fdr_down < 0.05)

df = res3$results %>%
  as_tibble %>%
  filter(celltype %in% c("Unknown", 'GABAergic SST interneuron')) %>%
  group_by(SubID, celltype, AD, chrom) %>%
  summarize( meanResid = mean(residuals))

fig = ggplot(df, aes(celltype, meanResid, fill=as.character(AD))) +
  geom_violin() +
  theme_classic() +
  theme(aspect.ratio=1) +
  facet_wrap(~chrom) +
  coord_flip()

ggsave("~/www/test.png", fig)

library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)

df_lm = res3$results %>%
  as_tibble %>%
  group_by(celltype, chrom) %>%
  do(broom.mixed::tidy(lmer(pmax(residuals,0) ~ AD + Sex + (1|SubID), .data)))



fig = df_lm %>% 
  # filter(term == "AD") %>%
  filter(term == "SexMale") %>%
  mutate(chrom = factor(chrom, rownames(sceAggr))) %>%
  mutate(fdr = p.adjust(p.value, "BH")) %>%
  ggplot(aes(celltype, estimate, color=pmin(4, -log10(fdr)*sign(estimate)))) +
    geom_point(size=.5) +
    geom_errorbar(aes(ymin=estimate - 1.96*std.error,ymax=estimate + 1.96*std.error), width=0) +
    theme_classic() +
    theme(aspect.ratio=1) +
    facet_wrap(~chrom) +
    geom_hline(yintercept=0, color="grey", linetype="dashed") +
    coord_flip() +
    scale_color_gradient2(name = "FDR", high="red", mid="grey", low="blue", limits=c(-4,4))

ggsave("~/www/test.png", fig)

# size factors
# batch effects and channel
# compare replicates
# how did old version work?




```


# Correlation in gain/loss scores across chromosomes





