---
title: "SEA_AD"
subtitle: 'SEA_AD'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
vignette: >
  %\VignetteIndexEntry{SEA_AD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---





<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/replication/SEA_AD
git pull 
R
rmarkdown::render("SEA_AD.Rmd");



# https://hoffmg01.hpc.mssm.edu/SEA_AD.html





FILE=/sc/arion/projects/CommonMind/leed62/ref/published/2024_SEA-AD_snRNA/SEAAD_A9_RNAseq_final-nuclei.2024-02-13.h5ad
../../../nps_ad/concat_h5ad.py -i <(echo $FILE) -d -o SEAAD_A9_RNAseq_final.h5ad

export R_LIBS_USER=
export R_LIBS=
# /sc/arion/projects/CommonMind/leed62/conda/envs/dreamlet430/bin/R --vanilla --quiet
.libPaths("/sc/arion/projects/CommonMind/leed62/conda/envs/dreamlet430/lib/R/library")

, obsm=FALSE, obsp=FALSE, uns=FALSE, var=FALSE,

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load packages
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(dreamlet)
library(scater)
library(GSEABase)
library(zenith)
library(ggrepel)
library(knitr)
library(kableExtra)
library(scattermore)
library(cowplot)
library(ggplot2)
library(viridis)
library(qvalue)
library(tidyverse)
library(RColorBrewer)
library(BiocParallel)
library(arrow)
library(formula.tools)
```


# Load data
```{r load.data}
# read H5AD file
# file = "/sc/arion/projects/CommonMind/leed62/ref/published/2024_SEA-AD_snRNA/SEAAD_A9_RNAseq_final-nuclei.2024-02-13.h5ad"
# sce = readH5AD(file, use_hdf5=TRUE, verbose=TRUE, layers=TRUE, version="0.8.0", reader="R")
sce = readRDS("/sc/arion/projects/psychAD/NPS-AD/freeze2_proc/241202_PsychAD_external_validations/241202_SEA-AD.sce.rds")

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "Subclass",  
    sample_id = "Donor.ID")
```



## Process pseudobulk data to estimate precision weights
```{r voom}
pb = pb[,pb$PMI != "Reference"]

pb$PMI = as.numeric(as.character(pb$PMI))
pb$Brain.pH = as.numeric(as.character(pb$Brain.pH))
pb$Age.at.Death = as.numeric(as.character(pb$Age.at.Death))
pb$Cognitive.Status = droplevels(pb$Cognitive.Status)

# Normalize and apply voomWithDreamWeights
form = ~ Sex + Age.at.Death + PMI + Brain.pH

res.proc = processAssays( pb, 
                          form,  
                          min.cells = 2,
                          min.count = 1,
                          min.samples = 4,
                          min.prop = 0.3,
                          BPPARAM = SnowParam(6))
```

### Show details of processing
```{r details}
details(res.proc) 
```

### Show voom-style mean-variance trends
```{r voom.plot, fig.height=16, fig.width=10}
# show voom plot for each cell clusters  
plotVoom( res.proc, ncol=4) 
```


# Variance partitioning analysis
```{r vp}
# run variance partitioning analysis
form = ~ Sex + Age.at.Death + PMI + Brain.pH + Cognitive.Status
vp.lst = fitVarPart( res.proc, form, BPPARAM = SnowParam(6, progressbar=TRUE))
```

```{r vp.plot, fig.height=16, fig.width=10}
# Summarize variance fractions genome-wide for each cell type
plotVarPart(sortCols(vp.lst), label.angle=60, ncol=4)   
```

# dreamlet
```{r dreamlet}
form = ~ Sex + Age.at.Death + PMI + Brain.pH + Cognitive.Status
fit = dreamlet(res.proc, form) 
```

# Volcano
```{r volcano, fig.height=9, fig.width=12}
plotVolcano(fit, "Cognitive.StatusDementia")
```

```{r write.file}
topTable(fit, coef = "Cognitive.StatusDementia", number=Inf) %>%
  write.table(file="SEA_AD.tsv", quote=FALSE, sep="\t", row.names=FALSE)
```







