---
title: "Concordance analysis of PsychENCODE"
subtitle: 'Signatures from multi-disease analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  DATASET: NULL
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/concordance/

git pull 
R

system("git pull"); rmarkdown::render("psychencode.Rmd")



# https://hoffmg01.hpc.mssm.edu/nps_ad//analysis/freeze2/concordance/


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = TRUE)
```


# Loading
## Libraries
```{r load.packages, cache=FALSE}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(ggplot2)
library(parallel)
library(heivr)
library(gtools)
library(ggcorrplot)
library(cowplot)
})
```

## CMC signature
```{r cmc}
file = "/sc/arion/projects/CommonMind/hoffman/cmc_signature/df_DE_results.RDS"
res.cmc = readRDS(file)

df.cmc = lapply(names(res.cmc), function(x){
  res.cmc[[x]]$DxSCZ %>%
    as_tibble %>%
    mutate(estimate = logFC, 
        std.error = logFC / t, 
        ID = Symbol, 
        statistic = t,
        p.value = P.Value,
        FDR.within =  adj.P.Val,
        assay = x) %>%
    select(ID, assay, estimate, std.error, statistic, p.value, FDR.within)
  })
df.cmc = bind_rows(df.cmc)

tab = table(df.cmc$ID)
exclude = names(tab[tab !=2])

df_filter = df.cmc %>%
  select(ID, estimate, assay) %>%
  filter(! ID %in% exclude) %>%
  pivot_wider(names_from = assay, values_from = estimate) 

cor(df_filter[,-1] %>% as.matrix)

```

## Define pi1 code
```{r pi1}
compute_pi1 = function(df){

  Y = df %>%
        select(assay, p.value, ID) %>%
        pivot_wider(names_from = "assay", values_from="p.value") %>% 
        select(-ID) 

  df_grid = expand.grid(assay1 = unique(colnames(Y)), 
                        assay2 = unique(colnames(Y))) 

  library(qvalue)
  get_pi1 = function(p){
    res <- tryCatch( pi0est(c(p, 1)), error = function(e) NULL)

    ifelse(is.null(res), NA, 1 - res$pi0)
  }

  df_pi1 = mclapply( 1:nrow(df_grid), function(i){
    k1 = df_grid$assay1[i] %>% as.character
    k2 = df_grid$assay2[i]%>% as.character

    df = Y[,c(k1, k2)]
    df = df[apply(df,1, function(x) all(!is.na(x))),]

    j = p.adjust(df[,1] %>% pull, "fdr") < 0.05

    pvals = df[j,2] %>% pull

    pi1 = get_pi1(pvals)

    data.frame(assay1 = k1, assay2 = k2, pi1 =pi1, nDE = sum(j) )
    }, mc.cores=4)
  df_pi1 = bind_rows(df_pi1) %>%
      mutate(assay1 = factor(assay1, colnames(Y))) %>%
      mutate(assay2 = factor(assay2, colnames(Y))) 

  df_pi1
}


plot_pi1 = function(df_pi1){
 
  df_pi1 %>%
       ggplot(aes(assay1, assay2, fill=pi1)) +
            geom_tile() +
            theme_classic() +
            theme(aspect.ratio=1, 
              legend.position = "none", 
              axis.text.x = element_text(angle = 90),
              plot.title = element_text(hjust = 0.5)) +
            scale_fill_gradient(low="white", high="red", limits=c(0,1)) 
}
```


# PsychENCODE
```{r pec}
files = dir("/sc/arion/projects/CommonMind/mpjanic/PEC/final_dl/final/", pattern="*.csv", full.names=TRUE)

res = mclapply(files, function(file){

  df = read.table(file, sep=',', row.names=1) %>%
      as_tibble 

  if( "logFC" %in% colnames(df)){
      df = df %>%
        rename(estimate = logFC,
                p.value = P.Value) %>%
        mutate(std.error = estimate/t)     
  }

  df_est = df %>%
        select(assay, ID, estimate) %>%
        pivot_wider(names_from = assay, 
          values_from = estimate)

  df_se = df %>%
        select(assay, ID, std.error) %>%
        pivot_wider(names_from = assay, 
          values_from = std.error)

  C.std = cor(df_est[,-1] %>% as.matrix, use="pairwise.complete.obs")

  df_pi1 = compute_pi1(df)

  hres = heivrPairs(df_est[,-1] %>% as.matrix, 
          df_se[,-1]^2 %>% as.matrix)

  C.het = pairsToMatrix(hres, "rho")

  list(C.std = C.std, C.het = C.het, df_pi1 = df_pi1)
}, mc.cores=6)
names(res) = gsub("\\.csv", "", basename(files))
```

```{r plots, fig.width=13}
lapply(names(res), function(id){
  message(id)

  fig1 = ggcorrplot(res[[id]]$C.std, title=paste(id, "std")) +
    theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90), aspect.ratio=1, 
              legend.position = "none")
  fig2 = ggcorrplot(res[[id]]$C.het, title=paste(id, "heivr")) +
    theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 90),legend.position = "none")

  fig3 = plot_pi1(res[[id]]$df_pi1) + ggtitle(id)
  plot_grid(fig1, fig2, fig3, align="hv", nrow=1)
})
```

## pairs
```{r pec.pair}
pairValues = tolower(c("SCZ/BP", "SCZ/ASD", "SCZ/MDD", "SCZ/PTSD"))

res = mclapply(pairValues, function(id){

  ids = unlist(strsplit(id, "/"))

  res = lapply(ids, function(id1){
    file = paste0("/sc/arion/projects/CommonMind/mpjanic/PEC/final_dl/final/", id1, ".csv")

    df = read.table(file, sep=',', row.names=1) %>%
        as_tibble 

    if( "logFC" %in% colnames(df)){
        df = df %>%
          rename(estimate = logFC,
                  p.value = P.Value) %>%
          mutate(std.error = estimate/t)     
    }

    df_est = df %>%
          mutate(id = id1) %>%
          select(id, assay, ID, estimate) 

    df_se = df %>%
          mutate(id = id1) %>%
          select(id, assay, ID, std.error) 

    list(df_est = df_est, df_se = df_se)     
    })
  names(res) = ids

  df_est = bind_rows(res[[1]]$df_est, res[[2]]$df_est) %>%
              mutate(assay = paste0(id, ' / ', assay)) %>%
              select(-id) %>%
              pivot_wider(names_from = assay, 
                values_from = estimate)

  df_se = bind_rows(res[[1]]$df_se, res[[2]]$df_se)%>%
              mutate(assay = paste0(id, ' / ', assay)) %>%
              select(-id) %>%
              pivot_wider(names_from = assay, 
                values_from = std.error)

  C.std = cor(df_est[,-1] %>% as.matrix,
              use="pairwise.complete.obs")

  hres = heivrPairs(df_est[,-1] %>% as.matrix, 
          df_se[,-1]^2 %>% as.matrix)

  C.het = pairsToMatrix(hres, "rho")

  list(C.std = C.std, C.het = C.het)
}, mc.cores=6)
names(res) = pairValues
```

```{r plots.pair, fig.width=13, fig.height=8, cache=FALSE}
lapply(names(res), function(id){
  message(id)

  fig1 = ggcorrplot(res[[id]]$C.std, title=paste(id, "std")) +
    theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90), aspect.ratio=1, 
              legend.position = "none")
  fig2 = ggcorrplot(res[[id]]$C.het, title=paste(id, "heivr")) +
    theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 90),legend.position = "none")

  plot_grid(fig1, fig2, align="hv", nrow=1)
})
```



