---
title: "Evaluate concordance based on formula"
subtitle: 'Automated analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: false
params:
  dataset: NULL
  variable_type: NULL
  ctst_key: NULL
  AnnoLevel: NULL
  SampleLevel: NULL
---



<!--- 

# https://hoffmg01.hpc.mssm.edu/nps_ad/analysis/freeze2/testing/compare_concordace.html

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/testing/
ml python git pandoc gcc/11.2.0
git pull origin master

rm -rf compare_concordace_cache/ compare_concordace_files

system("git pull origin master")
rmarkdown::render("compare_concordace.Rmd")


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r libs, cache=FALSE}
library(dreamlet)
library(tidyverse)
library(parallel)
library(RhpcBLASctl)
omp_set_num_threads(2)
```

# V1
```{r main}
# read PB
files = c(MSSM = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/MSSM_2024-02-01_16_17_PB_SubID_class.RDS", 
  HBCC = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/HBCC_2024-02-01_15_18_PB_SubID_class.RDS")
pbList = lapply( files, readRDS)
names(pbList) = names(files)

# read PB bulk
files = c(MSSM = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/MSSM_2024-02-01_16_17_PB_SubID_bulk.RDS", 
  HBCC = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/HBCC_2024-02-01_15_18_PB_SubID_bulk.RDS")
pbList2 = lapply( files, readRDS)
names(pbList2) = names(files)

assay(pbList[["MSSM"]], "bulk") = assay(pbList2[["MSSM"]], "bulk")
assay(pbList[["HBCC"]], "bulk") = assay(pbList2[["HBCC"]], "bulk")

for( dataset in names(pbList)){
  for( id in names(int_colData(pbList[[dataset]])$n_cells)){
    int_colData(pbList[[dataset]])$n_cells[[id]] = append(int_colData(pbList[[dataset]])$n_cells[[id]], c(bulk=100))
  }
}



# permute
# for( id in names(pbList) ){
#   v = ifelse(id == "MSSM", "c02x", "c08x")
#   values = colData(pbList[[id]])[[v]]
#   colData(pbList[[id]])[[v]] = sample(values)
# }

# processAssays
form = ~ Sex + scale(Age) + scale(PMI) + log(n_genes) + percent_mito + mito_genes + ribo_genes + mito_ribo + pH

res.procList = mclapply(pbList, function(pb){
  # res = processAssays(pb, ~1)

  # keep = outlierByAssay(res, nPC=5) %>%
  #   group_by(ID) %>%
  #   summarize(z2 = sort(z, decreasing=TRUE)[2]) %>%
  #   arrange(desc(z2)) %>%
  #   filter(z2 < 3) %>%
  #   pull(ID)

  # processAssays(pb[,keep], form)
  processAssays(pb, form)
  })
names(res.procList) = names(pbList)
```


```{r dreamlet}
# dreamlet
formList = list(MSSM = update(form, ~ c02x + .),
              HBCC = update(form, ~ c08x + .))

resList = mclapply(names(res.procList), function(id){
  dreamlet(res.procList[[id]], formList[[id]])
  })
names(resList) = names(res.procList)

tab = lapply(names(res.procList), function(id){
  co = ifelse(id == "MSSM", "c02xAD", "c08xSCZ")
  tab = topTable( resList[[id]], coef=co, number=Inf)
  tab$Dataset = id
  tab %>% as_tibble
  })

df = inner_join(tab[[1]], tab[[2]], by=c("assay", 'ID'))
```

```{r plots, cache=FALSE}
df %>%
  group_by(assay) %>%
  summarize(r = cor(logFC.x, logFC.y, method="sp"),
            r.mag = cor(loess(logFC.x ~ AveExpr.x)$residuals, 
                            loess(logFC.y ~ AveExpr.y)$residuals, 
                            method="sp"))

genes = intersect(tab[[1]]$ID, tab[[2]]$ID)
ct = assayNames(pbList[[1]])

Y1 = tab[[1]] %>%
      select(assay, logFC, ID) %>%
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC") 

Y2 = tab[[2]] %>%
      select(assay, logFC, ID) %>% 
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC")

Y = inner_join(Y1, Y2, by="ID")  

C = cor(Y[,-1], use="pair")

i = grep("\\.x$", rownames(C))
j = grep("\\.y$", colnames(C))
Csub = C[i,j]
Csub = Csub[order(rownames(Csub)), order(colnames(Csub))]

breaksList = seq(-1, 1, by=.025)

pheatmap::pheatmap(Csub, 
  cluster_rows=FALSE, 
  cluster_cols=FALSE, 
  display_numbers = round(Csub,2),
  cellheight = 30, 
  cellwidth = 30,
  color=colorRampPalette(c("navy", "white", "red"))(length(breaksList)),
  breaks=breaksList,
  main = "MSSM AD/CTRL vs HBCC SCZ/CTRL (standard)")
```

```{r pca, fig.width=9}
plotPCA(res.procList[[1]], size=1.5, maxOutlierZ=15)
plotPCA(res.procList[[2]], size=1.5, maxOutlierZ=15) 
```

## MSSM
```{r outliers1}
df_out = lapply( res.procList, outlierByAssay)
names(df_out) = names(res.procList)

res = df_out[["MSSM"]] %>%
  group_by(ID) %>%
  summarize(meanZ = mean(z)) %>%
  arrange(desc(meanZ))

head(res, 10)

hist(res$meanZ)
```

## HBCC
```{r outliers2}
res = df_out[["HBCC"]] %>%
  group_by(ID) %>%
  summarize(meanZ = mean(z)) %>%
  arrange(desc(meanZ))

head(res, 10)

hist(res$meanZ)
```



# V2

```{r proc2}
# processAssays
form = ~ Sex + scale(Age) + scale(PMI) + Source + log(n_genes) + TechPC1 + TechPC2 + TechPC3 + percent_mito + mito_genes + mito_ribo + ribo_genes

# res.procList = lapply(pbList, function(pb){
#   res = processAssays(pb, ~1)

#   keep = outlierByAssay(res, nPC=5) %>%
#     group_by(ID) %>%
#     summarize(z2 = sort(z, decreasing=TRUE)[2]) %>%
#     arrange(desc(z2)) %>%
#     filter(z2 < 3) %>%
#     pull(ID)

#   processAssays(pb[,keep], form)
#   })
# names(res.procList) = names(pbList)
```

```{r dreamlet2}
# dreamlet
formList = list(MSSM = update(form, ~ c02x + .),
              HBCC = update(form, ~ c08x + .))

resList = lapply(names(res.procList), function(id){
  dreamlet(res.procList[[id]], formList[[id]])
  })
names(resList) = names(res.procList)

tab = lapply(names(res.procList), function(id){
  co = ifelse(id == "MSSM", "c02x.L", "c08x.L")
  tab = topTable( resList[[id]], coef=co, number=Inf)
  tab$Dataset = id
  tab %>% as_tibble
  })

df = inner_join(tab[[1]], tab[[2]], by=c("assay", 'ID'))
```

```{r plots2, cache=FALSE}
df %>%
  group_by(assay) %>%
  summarize(r = cor(logFC.x, logFC.y, method="sp"),
            r.mag = cor(loess(logFC.x ~ AveExpr.x)$residuals, 
                            loess(logFC.y ~ AveExpr.y)$residuals, 
                            method="sp"))
 
genes = intersect(tab[[1]]$ID, tab[[2]]$ID)
ct = assayNames(pbList[[1]])

Y1 = tab[[1]] %>%
      select(assay, logFC, ID) %>%
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC") 

Y2 = tab[[2]] %>%
      select(assay, logFC, ID) %>% 
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC")

Y = inner_join(Y1, Y2, by="ID")  

C = cor(Y[,-1], use="pair")


i = grep("\\.x$", rownames(C))
j = grep("\\.y$", colnames(C))
Csub = C[i,j]
Csub = Csub[order(rownames(Csub)), order(colnames(Csub))]

breaksList = seq(-1, 1, by=.025)

pheatmap::pheatmap(Csub, 
  cluster_rows=FALSE, 
  cluster_cols=FALSE, 
  display_numbers = round(Csub,2),
  cellheight = 30, 
  cellwidth = 30,
  color=colorRampPalette(c("navy", "white", "red"))(length(breaksList)),
  breaks=breaksList,
  main = "MSSM AD/CTRL vs HBCC SCZ/CTRL (covs)")
```



# MORE PAIRS
```{r pairs}

library(arrow)
library(tidyverse)
library(parallel)

get_pi1 = function(p){
  res <- tryCatch( pi0est(c(p, 1)), error = function(e) NULL)

  ifelse(is.null(res), NA, 1 - res$pi0)
}

file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/topTable_combined.parquet"
df_all = read_parquet(file) %>%
          filter(AnnoLevel == "class" || AnnoLevel == "bulk") %>%
          rename(estimate = logFC)

file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/meta/res_meta.parquet"
df_meta = read_parquet(file) %>%
          filter(AnnoLevel == "class" || AnnoLevel == "bulk", 
            method == "FE") %>%
          rename(P.Value = p.value)

df_stack = bind_rows(df_all, df_meta)

df_coef = df_all %>%
  select(coef, Dataset) %>%
  unique


df_coef[grep("SC", df_coef$coef),]

getCohort = function(x){
  res = df_coef[grep(x, df_coef$coef),]$Dataset[1]
  ifelse(is.na(res), "meta-analysis", res)
}


make_plot = function(coef1, coef2){
  df1 = df_stack %>%
          filter(coef == coef1)%>%
          arrange(assay)

  df2 = df_stack %>%
          filter(coef == coef2) %>%
          arrange(assay)

  df_join = inner_join(df1, df2, by=c("assay", "ID"))


  # corr along diagonals
  df_join %>%
    group_by(assay) %>%
    summarize(r = cor(estimate.x, estimate.y, method="sp"), 
              n = length(estimate.x),
              se = sqrt((1-r^2)/ (n-2)))


  Y1 = df1 %>%
        select(assay, estimate, ID) %>%
        pivot_wider(names_from = "assay", values_from="estimate") 

  Y2 = df2 %>%
        select(assay, estimate, ID) %>%
        pivot_wider(names_from = "assay", values_from="estimate")

  Y = inner_join(Y1, Y2, by="ID") %>%
        select(-ID) 

  C = cor(Y, use="pair")

  main = paste0("x: ", coef1, " (", getCohort(coef1), ") | y: ", coef2, " (", getCohort(coef2), ")")

  # png("~/www/test.png", height=600, width=600)
  breaksList = seq(-1, 1, by=.025)

  pheatmap::pheatmap(C, 
    cluster_rows=FALSE, 
    cluster_cols=FALSE, 
    color=colorRampPalette(c("navy", "white", "red"))(length(breaksList)),
    breaks=breaksList, 
    main=main)
  # dev.off()
}


# meta-analysis of AD/control and SCZ control
coef1 = "m01x"
coef2 = "m05x"
make_plot(coef1, coef2)

coef1 = "c07xSCZ - c07xControl" # MSSM
coef2 = "c03xAD - c03xControl" # RUSH
make_plot(coef1, coef2)

coef1 = "c02xAD - c02xControl" # MSSM
coef2 = "c08xSCZ - c08xControl" # HBCC
make_plot(coef1, coef2)

coef1 = "c38xSCZ - c38xBD" # HBCC
coef2 = "c06xAD - c06xSCZ" # MSSM
make_plot(coef1, coef2)

coef1 = "c07xSCZ - c07xControl" # MSSM
coef2 = "c02xAD - c02xControl"  # MSSM
make_plot(coef1, coef2)

coef1 = "c03xAD - c03xControl" # RUSH
coef2 = "c08xSCZ - c08xControl" # HBCC
make_plot(coef1, coef2)


coef1 = "r10x.L" # AGING
coef2 = "c02xAD - c02xControl"  # MSSM
make_plot(coef1, coef2)

coef1 = "r10x.L" # AGING
coef2 = "m01x"  # MSSM
make_plot(coef1, coef2)

coef1 = "c08xSCZ - c08xControl" # HBCC
coef2 = "c07xSCZ - c07xControl" # MSSM
make_plot(coef1, coef2)

coef1 = "m05x" # SCZ
coef2 = "m20x" # APOE
make_plot(coef1, coef2)

coef1 = "m01x" # AD
coef2 = "m20x" # APOE
make_plot(coef1, coef2)
```



```{r exit1, cache=FALSE }
knitr::knit_exit()
```

# V3
```{r proc3}
# processAssays
form = ~ Sex + scale(Age) + scale(PMI) #+ Source + log(n_genes) + TechPC1 + TechPC2 + TechPC3 + percent_mito + mito_genes + mito_ribo + ribo_genes
res.procList = lapply(names(pbList), function(id){

  pb = pbList[[id]]

  # remove outliers
  keep = df_out[[id]] %>%
    group_by(ID) %>%
    summarize(meanZ = mean(z)) %>%
    arrange(desc(meanZ)) %>%
    filter(meanZ < 4) %>%
    pull(ID)

  processAssays(pb[,keep], form)
  })
names(res.procList) = names(pbList)
```

<!---
df_out = lapply( res.procList, outlierByAssay, nPC=5)
names(df_out) = names(res.procList)


df_out[[id]] %>%
  filter(z >5) %>%
  count(ID)


  summarize(table(ID))



keep = df_out[[id]] %>%
    group_by(assay) %>%
    mutate(fdr = p.adjust(pValue, "fdr")) %>%
    group_by(ID) %>%
    filter(fdr < 0.05) 


length(keep)



    %>%
    select(assay, ID)


    %>%
    pull(ID)

length(keep)




    summarize(meanZ = mean(z)) %>%
    arrange(desc(meanZ)) %>%
    filter(meanZ < 4) %>%
    pull(ID)

length(keep)
form = ~1
r1 = processAssays(pb, form, assays="EN")
r2 = processAssays(pb[,keep], form, assays="EN")

pdf("~/www/test.pdf")
plotPCA(r1, size=1.5, maxOutlierZ=15)
plotPCA(r2, size=1.5, maxOutlierZ=15) 
dev.off()


outlierByAssay(r1, nPC=5) %>%
  arrange(desc(z)) 


outlierByAssay(r2, nPC=2) %>%
  arrange(desc(z)) 


a = df_out[[id]] %>%
    filter(assay == "EN") %>%
    mutate(pValue = 2*pnorm(z, lower.tail=FALSE)) %>%
    pull(pValue)

--->


```{r pca2, fig.width=9}
plotPCA(res.procList[[1]], size=1.5, maxOutlierZ=15)
plotPCA(res.procList[[2]], size=1.5, maxOutlierZ=15)
```

```{r dreamlet3}
# dreamlet
formList = list(MSSM = update(form, ~ c02x + .),
              HBCC = update(form, ~ c08x + .))

resList = lapply(names(res.procList), function(id){
  dreamlet(res.procList[[id]], formList[[id]])
  })
names(resList) = names(res.procList)

tab = lapply(names(res.procList), function(id){
  co = ifelse(id == "MSSM", "c02xAD", "c08xSCZ")
  tab = topTable( resList[[id]], coef=co, number=Inf)
  tab$Dataset = id
  tab %>% as_tibble
  })

df = inner_join(tab[[1]], tab[[2]], by=c("assay", 'ID'))
```

```{r plots3, cache=FALSE}
df %>%
  group_by(assay) %>%
  summarize(r = cor(logFC.x, logFC.y, method="sp"),
            r.mag = cor(loess(logFC.x ~ AveExpr.x)$residuals, 
                            loess(logFC.y ~ AveExpr.y)$residuals, 
                            method="sp"))
 
genes = intersect(tab[[1]]$ID, tab[[2]]$ID)
ct = assayNames(pbList[[1]])

Y1 = tab[[1]] %>%
      select(assay, logFC, ID) %>%
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC") 

Y2 = tab[[2]] %>%
      select(assay, logFC, ID) %>% 
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC")

Y = inner_join(Y1, Y2, by="ID")  

C = cor(Y[,-1], use="pair")

i = grep("\\.x$", rownames(C))
j = grep("\\.y$", colnames(C))
Csub = C[i,j]
Csub = Csub[order(rownames(Csub)), order(colnames(Csub))]

breaksList = seq(-1, 1, by=.025)

pheatmap::pheatmap(Csub, 
  cluster_rows=FALSE, 
  cluster_cols=FALSE, 
  display_numbers = round(Csub,2),
  cellheight = 30, 
  cellwidth = 30,
  color=colorRampPalette(c("navy", "white", "red"))(length(breaksList)),
  breaks=breaksList,
  main = "MSSM AD/CTRL vs HBCC SCZ/CTRL (covs)")
```


# V4
```{r proc4}
# processAssays
form = ~ Sex + scale(Age) + scale(PMI) + Source + log(n_genes) + TechPC1 + TechPC2 + TechPC3 + percent_mito + mito_genes + mito_ribo + ribo_genes
res.procList = lapply(names(pbList), function(id){

  pb = pbList[[id]]

  # remove outliers
  keep = df_out[[id]] %>%
    group_by(ID) %>%
    summarize(meanZ = mean(z)) %>%
    arrange(desc(meanZ)) %>%
    filter(meanZ < 4) %>%
    pull(ID)

  processAssays(pb[,keep], form)
  })
names(res.procList) = names(pbList)
```

```{r dreamlet4}
# dreamlet
formList = list(MSSM = update(form, ~ c02x + .),
              HBCC = update(form, ~ c08x + .))

resList = lapply(names(res.procList), function(id){
  dreamlet(res.procList[[id]], formList[[id]])
  })
names(resList) = names(res.procList)

tab = lapply(names(res.procList), function(id){
  co = ifelse(id == "MSSM", "c02xAD", "c08xSCZ")
  tab = topTable( resList[[id]], coef=co, number=Inf)
  tab$Dataset = id
  tab %>% as_tibble
  })

df = inner_join(tab[[1]], tab[[2]], by=c("assay", 'ID'))
```

```{r plots4, cache=FALSE}
df %>%
  group_by(assay) %>%
  summarize(r = cor(logFC.x, logFC.y, method="sp"),
            r.mag = cor(loess(logFC.x ~ AveExpr.x)$residuals, 
                            loess(logFC.y ~ AveExpr.y)$residuals, 
                            method="sp"))
 
genes = intersect(tab[[1]]$ID, tab[[2]]$ID)
ct = assayNames(pbList[[1]])

Y1 = tab[[1]] %>%
      select(assay, logFC, ID) %>%
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC") 

Y2 = tab[[2]] %>%
      select(assay, logFC, ID) %>% 
      filter(ID %in% genes) %>%
      pivot_wider(names_from = "assay", values_from="logFC")

Y = inner_join(Y1, Y2, by="ID")  

C = cor(Y[,-1], use="pair")

i = grep("\\.x$", rownames(C))
j = grep("\\.y$", colnames(C))
Csub = C[i,j]
Csub = Csub[order(rownames(Csub)), order(colnames(Csub))]

breaksList = seq(-1, 1, by=.025)

pheatmap::pheatmap(Csub, 
  cluster_rows=FALSE, 
  cluster_cols=FALSE, 
  display_numbers = round(Csub,2),
  cellheight = 30, 
  cellwidth = 30,
  color=colorRampPalette(c("navy", "white", "red"))(length(breaksList)),
  breaks=breaksList,
  main = "MSSM AD/CTRL vs HBCC SCZ/CTRL (covs)")
```



# 1) colData() should match Samples.max
# 2) plotPCA after outliers removed

# CTRl comparson
# permuate labels
# remove TechPC's





