---
title: "Run dreamlet contrasts"
subtitle: 'Automated analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: false
params:
  dataset: NULL
  variable_type: NULL
  ctst_key: NULL
  AnnoLevel: NULL
  SampleLevel: NULL
---



<!--- 

# https://hoffmg01.hpc.mssm.edu/PsychAD_analysis/

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/testing/
ml python git pandoc
git pull origin master

# Create jobs
Rscript write_contrast_jobs.R

# Goto folder
cd /sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis

ls jobs/* | parallel -P1 "bsub < {}"

ls jobs/*crumblr* | parallel -P1 "bsub < {}"

# rmarkdown::render("run_dreamlet_contrasts.Rmd")


DIR=/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/testing/

variable_type="CAT"
ctst_key="HBCC_SCZ_BD_CTRL"
dataset="HBCC"
OUTFILE=/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/${ctst_key}/${ctst_key}
Rscript -e "rmarkdown::render(\"$DIR/run_dreamlet_contrasts.Rmd\", output_file = \"$OUTFILE\", 
params=list(dataset = \"$dataset\", variable_type = \"$variable_type\", ctst_key = \"$ctst_key\"))"


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = FALSE,
  cache.lazy = FALSE)
```


# Parameters

<font size="4">__Evaluating dataset:__ `r params$dataset` </font>

<font size="4">__Variable type:__ `r params$variable_type`</font>

<font size="4">__Contrast:__ `r params$ctst_key`</font>

<font size="4">__AnnoLevel:__ `r params$AnnoLevel`</font>

<font size="4">__SampleLevel:__ `r params$SampleLevel`</font>


Job script
`
```{r script, echo=FALSE, results="asis"}
res = with(params, paste(dataset, ctst_key, SampleLevel, AnnoLevel, "crumblr.lsf", sep="_"))
cat(res)
```
`

Initialize with this line of code to reproduce results
`
```{r init, echo=FALSE, results="asis"}
res = with(params, paste0('params = list(dataset = "', dataset, '",\n', 
  'variable_type = "', variable_type, '",\n', 
  'SampleLevel = "', SampleLevel, '",\n', 
  'AnnoLevel = "', AnnoLevel, '",\n', 
  'ctst_key = "', ctst_key, '")'))
cat(res)
```
`


```{r get.contrast}
# Load CONTRASTS and metadata
load("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/metadata/contrasts_for_dreamlet.Rdata")

suffix2 = with(params, gsub(paste0(dataset, "/", dataset, "/"), paste0(dataset, "/"), paste0(toupper(dataset), "/", ctst_key, "/", SampleLevel, "/", AnnoLevel)))

outpath = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/", suffix2)

ctr = CONTRASTS[[params$variable_type]][[params$ctst_key]]

# Remove contrasts that fail
if( ctr$variable == "c07x"){
  ctr$contrasts = ctr$contrasts[!grepl("c07xBD", ctr$contrasts)]
}

# make this a random effect
ctr$covariates_incl = gsub("Brain_bank", "(1|Brain_bank)", ctr$covariates_incl)
```


# Load data
```{r load}
suppressPackageStartupMessages({
library(dreamlet)
library(SingleCellExperiment)
library(tidyverse)
library(zenith)
library(qvalue)
library(cowplot)
})

# read processed data
path = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/processAssays/final/")
pattern = paste0(toupper(params$dataset), "_2024-01.*_processAssays_", params$SampleLevel, "_", params$AnnoLevel, ".RDS")
file = dir(path, pattern=pattern, full.names=TRUE)
if( length(file) == 2){                 
  a = file.info(file)$ctime
  file = ifelse(difftime(a[1], a[2]) > 0, file[1], file[2])
}

stopifnot(length(file) ==1)

res.proc = readRDS( file )

covariates_base = c("scale(Age)", "Sex", "scale(PMI)", "log(n_genes)", "TechPC1", "TechPC2", "TechPC3") 
if( params$SampleLevel == "Channel" ){
  covariates_base = c(covariates_base, "(1|SubID)")
}
```

# dreamlet analysis
```{r analysis}
# combine base covariance with testing variables
covariates = setdiff(union(covariates_base, ctr$covariates_incl), ctr$covariates_excl)

# user-specified formula
if( any(is.null(ctr$contrasts)) || any(is.na(ctr$contrasts)) ){
  form = paste0("~ ", ctr$variable, " + ", paste0(covariates, collapse=" + "))  
  form.vp = form
}else{
  form = paste0("~ 0 + ", ctr$variable, " + ", paste0(covariates, collapse=" + "))
  form.vp = paste0("~ (1|", ctr$variable, ") + ", paste0(covariates, collapse=" + "))
}
form = as.formula(form)
form.vp = as.formula(form.vp)

if( params$SampleLevel == "Channel"){
  # merge subject-level metadata with colData(res.proc)
  metadata_sub = metadata[metadata$SubID %in% colData(res.proc)$SubID,]
  idx = match( colData(res.proc)$SubID, metadata_sub$SubID)
}else{  
  metadata_sub = metadata[metadata$SubID %in% rownames(colData(res.proc)),]
  idx = match( rownames(colData(res.proc)), metadata_sub$SubID)
}

# test ordering
# df = cbind(as.character(colData(res.proc)$SubID), 
#   metadata_sub$SubID[idx])
# all.equal(df[,1], df[,2])

cols = colnames(metadata_sub) %in% colnames(colData(res.proc))
# colData(res.proc) = cbind(colData(res.proc), metadata_sub[idx,!cols])
res.proc@data = cbind(colData(res.proc), metadata_sub[idx,!cols])

bpparam = SnowParam(3)

if( any(is.na(ctr$contrasts)) ){
  ctr$contrasts = NULL
}

# run dreamlet
fit = dreamlet( res.proc, form, 
            contrasts = ctr$contrasts,
            BPPARAM = bpparam)
```


```{r mashr}
if( length(assayNames(fit)) > 1 ){
  if( !is.null(ctr$contrasts) & length(ctr$contrasts) == 1 ){   
    res_mash <- run_mash(fit, ctr$contrasts)
    file = paste0(outpath, "/res_mash.RDS")
    saveRDS(res_mash, file=file)
  }else if( !is.null(ctr$variable) & ctr$variable %in% coefNames(fit) ){   
    res_mash <- run_mash(fit, ctr$variable)
    file = paste0(outpath, "/res_mash.RDS")
    saveRDS(res_mash, file=file)
  }
}
```


```{r testExit, eval=(is.null(coefNames(fit)))}
print("No coefficients were esimated,\nlikely because variable of interest was NA")
knitr::knit_exit()
```


### Formulas
formula: 
```{r echo=FALSE} 
paste0(as.character(form), collapse=' ')
```

formula vp: 
```{r echo=FALSE} 
paste0(as.character(form.vp), collapse=' ')
```




# Gene set analysis
```{r zenith}
# Run zenith gene set analysis on result of dreamlet
go.gs = get_GeneOntology(to="SYMBOL")

if( params$variable_type == "ORD" ){
  
  pattern = paste0("^", ctr$variable)
  coef.test = grep(pattern, coefNames(fit), value=TRUE)

  res.zenith = zenith_gsa(fit, coef = coef.test, go.gs, progressbar=FALSE)
}else{     
  if( any(is.null(ctr$contrasts)) || any(is.na(ctr$contrasts)) ){   
    coef.test = ctr$variable
  }else{
    coef.test = ctr$contrasts 
  }

  res.zenith = lapply(coef.test, function(coef){
    zenith_gsa(fit, coef = coef, go.gs, progressbar=FALSE)
    })   
  res.zenith = do.call(rbind, res.zenith)
}
```

# Plot results
```{r plots}
if( ! dir.exists(outpath) ) dir.create(outpath)

# cell type order
ctorder = assayNames(fit)

# plotZenithResults
tmp = sapply( unique(res.zenith$coef), function(coef_key){

  df = res.zenith[res.zenith$coef == coef_key,,drop=FALSE]
  fig = plotZenithResults(df, 5, 1)
  file = paste0(outpath, "/zenith_", gsub(" ", "_", coef_key), ".pdf")
  ggsave(file=file, fig, height=40, width=20)
  fig
  })

# plotVolcano
tmp = sapply( unique(res.zenith$coef), function(coef_key){

  fig = plotVolcano( fit, coef = coef_key, assays=ctorder )
  file = paste0(outpath, "/plotVolcano_", gsub(" ", "_", coef_key), ".pdf")
  ggsave(file=file, fig, height=20)
  fig
  })

tmp = sapply( unique(res.zenith$coef), function(coef_key){

  fig = plotBeeswarm( fit, coef = coef_key)
  file = paste0(outpath, "/plotBeeswarm_", gsub(" ", "_", coef_key), ".pdf")
  ggsave(file=file, fig, height=20)
  fig
  })

estimatepi1 = function(p){
  tryCatch( 1 - qvalue(p)$pi0, 
    error=function(e) 0 )
}

# DE counts
df_DE = lapply( unique(res.zenith$coef), function(coef_key){

  topTable(fit, coef = coef_key, number=Inf ) %>%
    as_tibble %>%
    mutate(coef = coef_key) %>%
    group_by(coef, assay) %>%
    summarise( 
      nGenes = length(adj.P.Val), 
      nDE = sum(adj.P.Val < 0.05),
      pi1 = estimatepi1(P.Value)) %>%
    mutate(assay = factor(assay, ctorder)) 
})
df_DE = do.call(rbind, df_DE)

# plots
tmp = sapply( unique(res.zenith$coef), function(coef_key){

  df_de = df_DE[df_DE$coef == coef_key, , drop=FALSE]

  ymax = 1.05*max(df_de$nGenes)
  fig1 = ggplot(df_de, aes(nGenes, assay, fill=assay)) + 
      geom_bar(stat="identity") + 
      theme_classic() +
      theme(aspect.ratio=1, legend.position="none") +
      scale_x_continuous(limits=c(0,ymax), expand=c(0,0)) +
      xlab("# genes expressed") +
      ylab("Cell type") 

  ymax = max(1.05*max(df_de$nDE), 100)
  fig2 = ggplot(df_de, aes(nDE, assay, fill=assay)) + 
      geom_bar(stat="identity") + 
      theme_classic() +
      theme(aspect.ratio=1, legend.position="none", axis.text.y=element_blank()) +
      scale_x_continuous(limits=c(0,ymax), expand=c(0,0)) +
      xlab("# genes with FDR < 5%") +
      ylab('')

  fig3 = ggplot(df_de, aes(pi1, assay, fill=assay)) + 
      geom_bar(stat="identity") + 
      theme_classic() +
      theme(aspect.ratio=1, legend.position="none", axis.text.y=element_blank()) +
      scale_x_continuous(limits=c(0,1), expand=c(0,0)) +
      xlab(bquote(pi[1]))+
      ylab('')

  fig = plot_grid(fig1, fig2, fig3, labels=LETTERS[1:3], nrow=1, axis="tblr", align="hv")

  file = paste0(outpath, "/nDE_", gsub(" ", "_", coef_key), ".pdf")
  ggsave(file, fig, width=12)
  fig
})
```

# Save results
```{r save.results}
file = paste0(outpath, "/fit.RDS")
saveRDS(fit, file=file)

file = paste0(outpath, "/ctr.RDS")
saveRDS(ctr, file=file)

file = paste0(outpath, "/res_zenith.RDS")
saveRDS(res.zenith, file=file)

# file = paste0(outpath, "/res_mashr.RDS")
# saveRDS(res.mashr, file=file)

file = paste0(outpath, "/df_DE_counts.tsv")
write.table(df_DE, file, sep="\t", quote=FALSE, row.names=FALSE)

file = paste0(outpath, "/formula.txt")
write(as.character(form), file)

# save DE results
res = lapply(coef.test, function(coef_key){
  tab = topTable(fit, coef = coef_key, number=Inf )
  tab$coef = coef_key
  tab %>% 
    as_tibble
}) %>%
  bind_rows
res$Dataset = toupper(params$dataset)
res$SampleLevel = params$SampleLevel
res$AnnoLevel = params$AnnoLevel

file = paste0(outpath, "/topTable.tsv.gz")
write_tsv(res, file)

if( params$variable_type == "ORD" ){

  # save DE results
  tab = topTable(fit, coef = coef.test, number=Inf )
  tab$coef = "joint"

  file = paste0(outpath, "/topTable_joint.tsv")
  write.table(tab, file, sep="\t", quote=FALSE, row.names=FALSE)
  R.utils::gzip(file, overwrite=TRUE)
}
```






Session Info
<details>
```{r session, echo=FALSE}
sessionInfo()
```
</details>


