---
title: "Run crumblr contrasts"
subtitle: 'Automated analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  dataset: NULL
  variable_type: NULL
  ctst_key: NULL
---



<!--- 

# https://hoffmg01.hpc.mssm.edu/PsychAD_analysis/

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/testing/
ml python git pandoc
git pull origin master

# Create jobs
Rscript write_contrast_jobs.R

# Goto folder
cd /sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis

ls jobs/* | parallel -P1 "bsub < {}"

# rmarkdown::render("run_dreamlet_contrasts.Rmd")


DIR=/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/testing/

variable_type="CAT"
ctst_key="HBCC_SCZ_BD_CTRL"
dataset="HBCC"
OUTFILE=/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/${ctst_key}/${ctst_key}
Rscript -e "rmarkdown::render(\"$DIR/run_dreamlet_contrasts.Rmd\", output_file = \"$OUTFILE\", 
params=list(dataset = \"$dataset\", variable_type = \"$variable_type\", ctst_key = \"$ctst_key\"))"


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = FALSE,
  cache.lazy = FALSE)
```


```{r get.contrast}
# Load CONTRASTS and metadata
load("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/contrasts_for_dreamlet.Rdata")

# variable_type = "CAT"
# ctst_key = "HBCC_SCZ_BD_CTRL"
# dataset = "HBCC"
outpath = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/", params$ctst_key)
ctr = CONTRASTS[[params$variable_type]][[params$ctst_key]]

# if( ! dir.exists(outpath) ) dir.create(outpath)
```


<font size="5">__Evaluating dataset:__ `r params$dataset` </font>

<font size="5">__Variable type:__ `r params$variable_type`</font>

<font size="5">__Contrast:__ `r params$ctst_key`</font>



# Load data
```{r load}
suppressPackageStartupMessages({
library(dreamlet)
library(SingleCellExperiment)
library(tidyverse)
library(crumblr)
library(qvalue)
library(cowplot)
library(aplot)
library(ggtree)
library(tidyverse)})

# read processed data
path = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk//")
pattern = paste0(toupper(params$dataset), "_2023-02-28_.*_PB_Channel_subclass.RDS")
file = dir(path, pattern=pattern, full.names=TRUE)

pb = readRDS( file )

covariates_base = c("Age", "(1|Sex)", "PMI", "(1|SubID)", "(1|poolID)")
```

# crumblr analysis
```{r analysis}
# combine base covariance with testing variables
covariates = setdiff(union(covariates_base, ctr$covariates_incl), ctr$covariates_excl)

# user-specified formula
if( any(is.null(ctr$contrasts)) || any(is.na(ctr$contrasts)) ){
  form = paste0("~ ", ctr$variable, " + ", paste0(covariates, collapse=" + "))
}else{
  form = paste0("~ 0 + ", ctr$variable, " + ", paste0(covariates, collapse=" + "))
  form.vp = paste0("~ (1|", ctr$variable, ") + ", paste0(covariates, collapse=" + "))
}
form = as.formula(form)
form.vp = as.formula(form.vp)

# merge subject-level metadata with colData(res.proc)
metadata_sub = metadata[metadata$SubID %in% colData(pb)$SubID,]
idx = match( colData(pb)$SubID, metadata_sub$SubID)

# # test ordering
# df = cbind(as.character(colData(pb)$SubID), 
#   metadata_sub$SubID[idx])
# all.equal(df[,1], df[,2])

cols = colnames(metadata_sub) %in% colnames(colData(pb))
colData(pb) = cbind(colData(pb), metadata_sub[idx,!cols])

if( any(is.null(ctr$contrasts)) || any(is.na(ctr$contrasts)) ){
  ctr$contrasts = NULL
}

# crumblr + dream
cobj = crumblr(cellCounts(pb))

# variance partitioning
idx = !is.na(colData(pb)[,ctr$variable])
vp.c = fitExtractVarPartModel(cobj[,idx], form.vp, colData(pb)[idx,])
fig.vp = plotPercentBars( sortCols(vp.c) )

plotVarPart(sortCols(vp.c), label.angle=60, ncol=4) + theme(aspect.ratio=1)

L = makeContrastsDream(form, as.data.frame(colData(pb)), contrasts = ctr$contrasts )
fit = dream( cobj, form, colData(pb), L = L)
fit = eBayes(fit)
```

```{r topTable, results="asis"}
res = lapply(ctr$contrasts, function(ctst){
  topTable(fit, coef=ctst, number=Inf) %>%
    kable(caption = ctst) 
})
kables(res)
```


### Multivariate test along hierarchy
```{r sd, fig.width=10, fig.height=5}
hc = buildClusterTreeFromPB(pb)

lapply(ctr$contrasts, function(ctst){
  res = treeTest( fit, cobj, hc, coef=ctst)

  fig1 = plotTreeTest(res) + xlim(0, 15) + theme(legend.position="none") + ggtitle(ctst)

  tab = topTable(fit, coef=ctst, number=Inf)

  tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig1)))
  tab$se = with(tab, logFC/t)

  fig2 = ggplot(tab, aes(celltype, logFC)) + 
    geom_hline(yintercept=0, linetype="dashed", color="grey", size=1) +
    geom_errorbar(aes(ymin = logFC - 1.96*se, ymax = logFC + 1.96*se), width=0) +
    geom_point(color="dodgerblue") +
    theme_classic() +
    coord_flip() +
    xlab('') + 
    ylab("Effect size") +
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank())

  # combine plots
  fig2 %>% insert_left(fig1) %>% insert_right(fig.vp)
})
```





# Save results
```{r save.results}
file = paste0(outpath, "/fit_crumblr.RDS")
saveRDS(fit, file=file)
```






Session Info
<details>
```{r session, echo=FALSE}
sessionInfo()
```
</details>


