---
title: "Compare crumblr analysis"
subtitle: 'Automated analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: false
params:
  dataset: NULL
  variable_type: NULL
  ctst_key: NULL
  AnnoLevel: NULL
  SampleLevel: NULL
---


<!---
cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/revision/replication
R
system("git pull"); rmarkdown::render("compare_crumblr.Rmd")

--->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = FALSE,
  cache.lazy = FALSE)
```

# Load packages
```{r load.pkgs, cache=FALSE}
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(arrow)
library(broom)
library(metafor)
library(kableExtra)
```

```{r load}
file = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/replication/celltype_mapping.tsv"
df_celltype = read_tsv( file ) %>%
            rename(CellType = PsychAD)

file = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/replication/Mathys_2023/Mathys_Cell_2023_Cell_Type_crumblr.parquet"
res.mathys = read_parquet(file) %>%
        rename(CellType1 = CellType) %>%
        filter(!grepl("order", coefSet))

file = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/replication/SEA_AD/SEA_AD_crumblr.parquet"
res.seaad = read_parquet(file)%>%
        rename(CellType1 = CellType)

file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/topTable_combined_crumblr.tsv.gz"
res.pad = read_tsv(file)

make_plot = function(traitset){

  # MSSM 
  df1 = res.pad %>%
    filter(coef == traitset["MSSM"]) %>%
    filter(AnnoLevel == "subclass")

  # Rush
  df2 = res.pad %>%
    filter(coef == traitset["RUSH"]) %>%
    filter(AnnoLevel == "subclass")

  # PsychAD
  df = bind_rows(df1, df2) %>%
    mutate(se = logFC / t) %>%
    group_by(CellType) %>%
    group_modify(~ tidy(rma(yi = logFC, sei = se, method = "FE", data=.))) %>%
    select(-term, -type)

  # join Mathys
  df_join1 = df %>%
    left_join(df_celltype %>% 
      filter(annotationLevel == "subclass"), by="CellType" ) %>%
    rename(CellType1 = Mathys_cell_type) %>%
    # rename(CellType1 = Mathys_major_cell_type) %>%
    # select(-SEA_AD_supertype, -Mathys_cell_type, -SEA_AD_subclass) %>%
    inner_join(res.mathys %>% filter(trait == traitset["Mathys"]), by="CellType1") %>%
    mutate(se = logFC / stat) %>%
    mutate(Dataset = "Mathys")

  # join SEAAD
  df_join2 = df %>%
    left_join(df_celltype %>% 
      filter(annotationLevel == "subclass"), by="CellType" ) %>%
    rename(CellType1 = SEA_AD_subclass) %>%
    inner_join(res.seaad %>% filter(trait == traitset["SEAAD"]), by="CellType1") %>%
    mutate(se = logFC / stat) %>%
    mutate(Dataset = "SEAAD")

  df_join = bind_rows(df_join1, df_join2)

  res = lapply( unique(df_join$Dataset), function(ds){
    fit = with(df_join[df_join$Dataset == ds,], cor.test(logFC, estimate, method="spearman"))
    n = nrow(df_join[df_join$Dataset == ds,])
    se = sqrt((1-fit$estimate^2) / (n-2))
    data.frame(Dataset = ds, 
      rho = fit$estimate, 
      se = se,
      p.value = fit$p.value)
  })
  res = do.call(rbind, res)   

  fig = df_join %>%
        mutate(label = paste(CellType, CellType1, sep=' / ')) %>%
        ggplot(aes(estimate, logFC, label=label)) +
          geom_vline(xintercept=0, linetype="dashed") +
          geom_hline(yintercept=0, linetype="dashed") +

          geom_errorbar(aes(xmin=estimate - 1.96*std.error, xmax=estimate + 1.96*std.error), width=0, alpha = .4, color="grey70") +
          geom_errorbar(aes(ymin=logFC - 1.96*se, ymax=logFC + 1.96*se), width=0, alpha = .4, color="grey70") +
          geom_text_repel(box.padding=1) +         
          geom_smooth(method="lm", color="red", se=FALSE) +
          geom_point() +
          theme_classic() +
          theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) +
          xlab("Estimate (PsychAD)")+
          ylab("Estimate") +
          coord_cartesian(expand=FALSE) +
          facet_wrap(~Dataset, ncol=1, scales="free_y") 

  list(fig = fig, res = res, df_join = df_join)
}
```

<!----
# AD
```{r ad, eval=FALSE}
traitset = c(MSSM = "c02xAD - c02xControl", RUSH = "c03xAD - c03xControl", Mathys = "ADdiag2types", SEAAD = 'none')
res = make_plot( traitset ) 
res$fig + ggtitle("AD")
```
--->

# Dementia (cogdx/CDR)
```{r dementia, fig.height=12}
traitset = c(MSSM = "r05x.L", RUSH = "r06x.L", Mathys = "cogdx", SEAAD = "Cognitive.Status")
res = make_plot( traitset ) 
res$fig + ggtitle("Dementia")
res$res %>%
  kbl %>%
  kable_styling(full_width = FALSE)
df_merge = res$df_join
```

```{r dementia2, fig.height=12}
traitset = c(MSSM = "r09x.L", RUSH = "r09x.L", Mathys = "cogdx", SEAAD = "Cognitive.Status")
res = make_plot( traitset ) 
res$fig + ggtitle("Dementia")
res$res %>%
  kbl %>%
  kable_styling(full_width = FALSE)
```

# Braak
```{r braak, fig.height=12}
traitset = c(MSSM = "r01x.L", RUSH = "r02x.L", Mathys = "braaksc", SEAAD = "Braak.value")
res = make_plot( traitset ) 
res$fig + ggtitle("Braak")
res$res %>%
  kbl %>%
  kable_styling(full_width = FALSE)
df_merge = rbind(df_merge, res$df_join)
```

# CERAD
```{r cerad, fig.height=12}
traitset = c(MSSM = "r03x.L", RUSH = "r04x.L", Mathys = "CERAD", SEAAD = "CERAD.value")
res = make_plot( traitset ) 
res$fig + ggtitle("CERAD")
res$res %>%
  kbl %>%
  kable_styling(full_width = FALSE)
df_merge = rbind(df_merge, res$df_join)
```


```{r joint}
library(lmerTest)
library(RNOmni)

df_merge2 = df_merge %>%
  select(CellType, estimate, logFC, Dataset, trait)

df_merge2$trait[df_merge2$trait == "Braak.value"] = "Braak" 
df_merge2$trait[df_merge2$trait == "braaksc"] = "Braak" 
df_merge2$trait[df_merge2$trait == "CERAD"] = "CERAD" 
df_merge2$trait[df_merge2$trait == "CERAD.value"] = "CERAD" 
df_merge2$trait[df_merge2$trait == "cogdx"] = "cogdx" 
df_merge2$trait[df_merge2$trait == "Cognitive.Status"] = "cogdx" 
table(df_merge2$trait)

# Test relationship between logFC for all traits jointly
# using inverse normal transform
fit = lmer(RankNorm(logFC) ~ RankNorm(estimate) + Dataset + (1|trait), df_merge)

coef(summary(fit))
```




















