---
title: "Single-cell atlas reveals correlates of high cognitive function, dementia, and resilience to Alzheimer's disease pathology"
subtitle: 'NPS Symptoms: replicate of weight phenotype'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
vignette: >
  %\VignetteIndexEntry{Single-cell atlas reveals correlates of high cognitive function, dementia, and resilience to Alzheimers disease pathology}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---





<!--- 


cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/revision/replication/
R

system("git pull"); rmarkdown::render("weight_phenotype.Rmd");


# https://hoffmg01.dmz.hpc.mssm.edu/revision/replication/weight_phenotype.html


--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load packages
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(dreamlet)
library(cowplot)
library(ggrepel)
library(ggplot2)
library(tidyverse)
library(metafor)
library(crumblr)
```


# in PsychAD
- c301x: TRUE if bmiChange < -2; FALSE otherwise
- c302x: TRUE if bmiChange < -2; FALSE if bmiChange > +2 ; otherwise NA
- c303x: TRUE if bmiChange <   0; FALSE; otherwise NA
- c304x: TRUE if bmiChange < -2; FALSE if bmiChange > +0; NA
- c305x - c308x: the same as above but with stronger criteria for AD presence (note we are only interested about neuropsychiatric symptoms of those donors who are AD).

```{r psychAD, eval=FALSE}
df_pheno = read_csv("Mathys_2023/rosmap_neuropsych_1.csv")

# PsychAD
#########
params = list(dataset = "FULL", AnnoLevel = "subclass", SampleLevel="SubID", variable_type="CAT", ctst_key ="AD_strict__AD_resilient__controls" )
path = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/")
pattern = paste0(toupper(params$dataset), "_2024-02.*_PB_", params$SampleLevel, "_", params$AnnoLevel, ".RDS")
file = dir(path, pattern=pattern, full.names=TRUE)

pb = readRDS( file )


# Construct regression contrasts

covariates_base = c("scale(Age)", "as.numeric(Sex)")#, "scale(PMI)", "TechPC1", "TechPC2", "TechPC3")  # "log(n_genes)"
if( params$SampleLevel == "Channel" ){
  covariates_base = c(covariates_base, "(1|SubID)")
}

# Load CONTRASTS and metadata
# synapse: syn51114763
load("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/metadata/contrasts_for_dreamlet.Rdata")

# PRS values
file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/prs.labels"
df_prs = read.table(file)$V1

# append to CONTRASTS[["NUM"]]
# example: CONTRASTS[["NUM"]][['MSSM_Cognitive_and_Tau_Resilience']]
prs.lst = lapply(df_prs, function(x){
  list(name = x, contrasts = NA, variable = paste0('scale(', x, ')'), covariates_incl='Brain_bank', covariates_excl = NULL)
  })
names(prs.lst) = df_prs

prs.lst = lapply( c("HBCC", "MSSM", "RUSH", "FULL"), function(cohort){

  tmp = prs.lst
  names(tmp) = paste0(cohort, '_', names(tmp))
  tmp
  })
prs.lst = unlist(prs.lst, recursive=FALSE)

CONTRASTS[["NUM"]] = append(CONTRASTS[["NUM"]], prs.lst)

suffix2 = with(params, gsub(paste0(dataset, "/", dataset, "/"), paste0(dataset, "/"), paste0(toupper(dataset), "/", ctst_key, "/", SampleLevel, "/", AnnoLevel)))

outpath = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/", suffix2)

ctr = CONTRASTS[[params$variable_type]][[params$ctst_key]]

# Remove contrasts that fail
# if( ctr$variable == "c07x"){
#   ctr$contrasts = ctr$contrasts[!grepl("c07xBD", ctr$contrasts)]
# }

# make this a random effect
ctr$covariates_incl = gsub("Brain_bank", "(1|Brain_bank)", ctr$covariates_incl)


# combine base covariance with testing variables
covariates = setdiff(union(covariates_base, ctr$covariates_incl), ctr$covariates_excl)

# user-specified formula
if( any(is.null(ctr$contrasts)) || any(is.na(ctr$contrasts)) ){
  form = paste0("~ ", ctr$variable, " + ", paste0(covariates, collapse=" + "))
  form.vp = form
}else{
  form = paste0("~ 0 + ", ctr$variable, " + ", paste0(covariates, collapse=" + "))
  form.vp = paste0("~ (1|", ctr$variable, ") + ", paste0(covariates, collapse=" + "))
}
form = as.formula(form)
form.vp = as.formula(form.vp)

if( params$SampleLevel == "Channel"){
  # merge subject-level metadata with colData(res.proc)
  metadata_sub = metadata[metadata$SubID %in% colData(pb)$SubID,]
  idx = match( colData(pb)$SubID, metadata_sub$SubID)
}else{  
  metadata_sub = metadata[metadata$SubID %in% rownames(colData(pb)),]
  idx = match( rownames(colData(pb)), metadata_sub$SubID)
}

pb2 = pb[,idx]

# keep shared IDs
ids = intersect(paste0("R", df_pheno$projid), colnames(pb2))
df_pheno_sub = df_pheno[paste0("R", df_pheno$projid) %in% ids,]
pb_sub = pb[,colnames(pb) %in% ids,]

i = match(ids, colnames(pb_sub))
pb_sub = pb_sub[,i]

i = match(ids, paste0("R", df_pheno_sub$projid))
df_pheno_sub = df_pheno_sub[i,]

identical(paste0("R", df_pheno_sub$projid), colnames(pb_sub))

info = cbind(colData(pb_sub), df_pheno_sub)

saveRDS(cellCounts(pb_sub), file="cellCounts_PsychAD.RDS")
saveRDS(info, file="info_PsychAD.RDS")
```

```{r crumblr, fig.height=12}
info = readRDS("info_PsychAD.RDS")
df_cellCounts = readRDS("cellCounts_PsychAD.RDS")

cobj = crumblr(df_cellCounts)

form.base = ~ scale(Age) + Sex + scale(PMI)

ctrst = grep("c30\\d", colnames(info), value=TRUE)

res.rosmap = lapply(ctrst, function(variable){

  form = update(form.base, paste(" ~ . + ", variable))

  fit = dream( cobj, form, info)
  fit = eBayes(fit)

  coef = last(colnames(coef(fit)))
  topTable(fit, coef=coef, number=Inf) %>%
    mutate(Coef = coef) %>%
    rownames_to_column("CellType1")
}) %>%
  bind_rows %>%
  as_tibble

res.rosmap %>%
  mutate(Coef = gsub("WeightLoss_PMA", "", Coef)) %>%
  # filter(Coef == "c306x") %>%
  ggplot(aes(Coef, CellType1, fill=logFC)) +
    geom_tile() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_equal() +
    scale_fill_gradient2(low="blue", mid="white", high="red") +
    ylab("") +
    ggtitle("ROSMAP")
```


```{r plot1, fig.height=12}
res.rosmap %>%
  mutate(Coef = gsub("WeightLoss_PMA", "", Coef)) %>%
  filter(Coef == "c306x") %>%
  ggplot(aes(Coef, CellType1, fill=logFC)) +
    geom_tile() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_equal() +
    scale_fill_gradient2(low="blue", mid="white", high="red") +
    ylab("") +
    ggtitle("ROSMAP + c306x")
```


```{r plot2, fig.height=6}
df6 = res.rosmap %>%
  mutate(se = logFC / t) %>%
  mutate(Coef = gsub("WeightLoss_PMA", "", Coef)) %>%
  filter(Coef == "c306x") %>%
  rename(CellType = CellType1)

write.csv(df6, file="res_c306x.csv", row.names=FALSE, quote=FALSE)

df6 %>%
  ggplot(aes(logFC, CellType)) +
    geom_point() +
    geom_errorbar(aes(xmin = logFC - se, xmax = logFC + se), width=0) +
    theme_classic() +
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) +
    ggtitle("ROSMAP c306x") +
    geom_vline(xintercept=0, color="grey50", linetype="dashed")
```

```{r plot3, fig.height=4}
res.rosmap %>%
  mutate(se = logFC / t) %>%
  mutate(Coef = gsub("WeightLoss_PMA", "", Coef)) %>%
  filter(Coef == "c306x") %>%
  filter(grepl("EN", CellType1)) %>%
  ggplot(aes(logFC, CellType1)) +
    geom_point() +
    geom_errorbar(aes(xmin = logFC - se, xmax = logFC + se), width=0) +
    theme_classic() +
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + 
    ggtitle("ROSMAP c306x") +
    geom_vline(xintercept=0, color="grey50", linetype="dashed")
```

```{r mssm, fig.width=10, fig.height=10}
file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/analysis/results/topTable_combined_crumblr.tsv.gz"
res.mssm = read_tsv(file) %>%
          filter(coef == "c91xWeightLoss_PMA - c91xControl") %>%
          filter(AnnoLevel == "subclass")

resList = lapply( unique(res.rosmap$Coef), function(v){
  df_merge = res.rosmap %>%
              filter(Coef == v) %>%
              rename(CellType = CellType1) %>%
              inner_join(res.mssm, by="CellType") %>%
              mutate(se.x = logFC.x / t.x) %>%
              mutate(se.y = logFC.y / t.y) 

  fig = df_merge %>%
    ggplot(aes(logFC.x, logFC.y, label = CellType)) +
      geom_hline(yintercept=0, color="grey50", linetype="dashed") +    
      geom_vline(xintercept=0, color="grey50", linetype="dashed") +
      geom_errorbar(aes(
        ymin = logFC.y - 1.96*se.y,
        ymax = logFC.y + 1.96*se.y),
        width=0, color="grey50", alpha=.4) + 
      geom_errorbar(aes(
        xmin = logFC.x - 1.96*se.x,
        xmax = logFC.x + 1.96*se.x),
        width=0, color="grey50", alpha=.4) + 
      geom_point() +
      theme_classic() +
      theme(aspect.ratio=1) +
      geom_text_repel(box.padding=0.5) +
      geom_smooth(method = 'lm', color="red", se=FALSE) +
      xlab("logFC (ROSMAP)") +
      ylab("logFC (MSSM)") +
      ggtitle(v) + 
      coord_flip()

    res = lapply(seq(nrow(df_merge)), function(i){
      fit = with(df_merge[i,], rma(yi = c(logFC.x, logFC.y), sei = c(se.x, se.y), method="FE")) 

      data.frame(Coef = v, 
        CellType = df_merge$CellType[i], 
        estimate = fit$beta, 
        se = fit$se,
        pvalue = fit$pval,
        df_merge[i,])
    }) %>%
    bind_rows

    list(res = res, fig = fig)
})
names(resList) = unique(res.rosmap$Coef)

figList = lapply(resList, function(x) x$fig)
plot_grid(plotlist = figList)

res = lapply(resList, function(x) x$res) %>%
  bind_rows %>%
  as_tibble

res %>%
  ggplot(aes(estimate, CellType)) +
    geom_errorbar(aes(
      xmin = estimate - 1.96*se,
      xmax = estimate + 1.96*se),
      width=0, color="grey50", alpha=.4) + 
    geom_point() +    
    theme_classic() +
    theme(aspect.ratio=1) +
    geom_vline(xintercept=0, color="grey50", linetype="dashed") +
    facet_wrap(~Coef) +
    ggtitle("Meta-analysis")
```

```{r meta}
res %>%
  filter(Coef == "c306xWeightLoss_PMA") %>%
  ggplot(aes(estimate, CellType)) +
    geom_errorbar(aes(
      xmin = estimate - 1.96*se,
      xmax = estimate + 1.96*se),
      width=0, color="grey50", alpha=.4) + 
    geom_point() +    
    theme_classic() +
    theme(aspect.ratio=1) +
    geom_vline(xintercept=0, color="grey50", linetype="dashed") +
    facet_wrap(~Coef) +
    ggtitle("Meta-analysis")
```

```{r plot4, cache=FALSE}
resList[['c306xWeightLoss_PMA']]$fig
```




```{r heatmap_meta, cache=FALSE, fig.height=10}
res2 = res %>%
  filter(Coef == "c306xWeightLoss_PMA") %>%
  select(Coef, CellType, estimate, se, logFC.x, t.x, logFC.y, t.y )

res3 = res2 %>%
  select(CellType, estimate, se) %>%
  mutate(Dataset = "Meta-analysis") %>%
  bind_rows(res2 %>%
    select(CellType, t.x, logFC.x) %>%
    mutate(se = logFC.x / t.x) %>%
    rename(estimate = logFC.x) %>%
    select(CellType, estimate, se) %>%
    mutate(Dataset = "ROSMAP")) %>%
  bind_rows(res2 %>%
    select(CellType, t.y, logFC.y) %>%
    mutate(se = logFC.y / t.y) %>%
    rename(estimate = logFC.y) %>%
    select(CellType, estimate, se) %>%
    mutate(Dataset = "MSSM"))

res3 %>% 
  mutate(Dataset = factor(Dataset, c("MSSM", "ROSMAP", "Meta-analysis"))) %>%
  ggplot(aes(Dataset, CellType, fill=estimate)) +
    geom_tile() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_equal() +
    scale_fill_gradient2(low="blue", mid="white", high="red", name="logFC") +
    ylab("") +
    ggtitle("c306x")

res3 %>% 
  mutate(Dataset = factor(Dataset, c("MSSM", "ROSMAP", "Meta-analysis"))) %>%
  ggplot(aes(Dataset, CellType, fill=estimate / se)) +
    geom_tile() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_equal() +
    scale_fill_gradient2(low="blue", mid="white", high="red", name="t statistic") +
    ylab("") +
    ggtitle("c306x")
```









