
--
title: "Gene expression of XIST/UTY"
subtitle: 'For concordance analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze_v2
ml python git
git pull
R --vanilla

system("git pull"); rmarkdown::render("get_sex_expression.Rmd");


# https://hoffmg01.u.hpc.mssm.edu/eval_methods/dreamlet/mathys_Nature_2019.html

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r load.packages, cache=FALSE}
# Use cache=FALSE so that package are fully loaded each time
# This ensures that forks within mclapply() have these loaded
# Othewise, mclapply() not have access to these libraries and will fail 
#   unless the libraries are manually loaded within each fork
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(dreamlet)
library(scater)
library(mclust)
library(tidyverse)

setAutoBlockSize(1e9)
```


```{r read.files.v1}
# Evaluate pseudobulk on each H5AD
folder = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad-by-donor/"

files = dir(folder, pattern="*.h5ad", full.names=TRUE)[1:200]

genes = c("ENSG00000183878_index", "ENSG00000229807_index")

df_all = lapply(files, function(file){

  message( match(file, files))
  sce = readH5AD(file, use_hdf5=TRUE)
    
  # normalize gene expression
  sce <- computeLibraryFactors(sce, assay.type="X")
  sce <- logNormCounts(sce, assay.type="X")

  df = data.frame(t(assay(sce[genes,], "logcounts")))
  colnames(df)[colnames(df) == 'ENSG00000183878_index'] = 'UTY'
  colnames(df)[colnames(df) == 'ENSG00000229807_index'] = 'XIST'
  df$SubID = sce$SubID_cs
  df$set = sce$set
  df
})
df_all = do.call(rbind, df_all)

# read metadata
df_meta = read_csv("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/metadata/clinical_metadata_full.csv", show_col_types=FALSE, progress=FALSE)

df_merge = left_join(df_all, df_meta[,c('SubID', 'Brain_bank', 'Sex')], by='SubID')
df_merge$Sex = factor(df_merge$Sex, c("Female", "Male"))
```


```{r predictor, cache=FALSE}
fit = glm(Sex ~ XIST*UTY, df_merge, family=binomial())

calcVarPart(fit)

dsgn = data.frame(model.matrix(~ XIST*UTY, df_merge))
df_merge$pred = predict(fit, dsgn, type="response")
```


```{r plot3, fig.width=7, fig.height=7, cache=FALSE}
df_merge %>%
  as_tibble %>%
  group_by(SubID) %>%
  summarize( Sex=Sex[1], Predicted.sex = mean(pred))  %>%
  arrange(Sex) %>%
  ggplot(aes(Sex, Predicted.sex)) + 
    geom_violin(aes(fill=Sex), scale="width") +
    geom_boxplot(width=0.07, fill="grey", outlier.colour='black') +
    theme_classic() +
    theme(aspect.ratio=1) + 
    scale_fill_manual(name="Labled sex", values=c("red", "blue")) + 
    scale_y_continuous(limits=c(0,1), expand=c(0,0))
```





```{r exit, cache=FALSE}
knitr::knit_exit(1)
```




```{r read.files, eval=FALSE}
# Combine H5AD's into one SCE, them copute pseudobulk

folder = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad-by-donor/"

files = dir(folder, pattern="*.h5ad", full.names=TRUE)

sceList = lapply(files, function(file){
  sce = readH5AD(file, use_hdf5=TRUE)
  colnames(sce) = paste0(sce$SubID_cs[1], "_", colnames(sce))
  sce
})

# get shared genes
genes = Reduce(intersect, lapply(sceList, rownames))

# Create SCE using only shared genes
sce = do.call(cbind, lapply(sceList[1:5], function(x) x[genes,]))

# Create pseudobulk
sce$constant = "counts"
sce$id = paste0(sce$SubID_cs, "_", sce$rep)

pb = aggregateToPseudoBulk(sce,
  assay = "X",     
  cluster_id = "constant",  
  sample_id = "id",
  verbose = TRUE)

# normalize gene expression
pb <- computeLibraryFactors(pb)
pb <- logNormCounts(pb)
```

/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/metadata/clinical_metadata_full.csv

```{r read.files.v2}
# Evaluate pseudobulk on each H5AD
folder = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad-by-donor/"

files = dir(folder, pattern="*.h5ad", full.names=TRUE)

pbList = lapply(files, function(file){

  message( match(file, files))
  sce = readH5AD(file, use_hdf5=TRUE)
    
  sce$constant = "counts"
  sce$id = paste0(sce$SubID_cs, "_", sce$rep)

  pb = aggregateToPseudoBulk(sce,
    assay = "X",     
    cluster_id = "constant",  
    sample_id = "id",
    verbose=FALSE)

  # normalize gene expression
  pb <- computeLibraryFactors(pb)
  pb <- logNormCounts(pb)

  pb
})

# colData must have same columns
cols = lapply(pbList, function(x) colnames(colData(x)))
cols = Reduce(intersect, cols)

genes = c("ENSG00000183878_index", "ENSG00000229807_index")
pb = do.call(cbind, lapply(pbList, function(x){
  x = x[genes,]
  colData(x) = colData(x)[,cols]
  x
  }))
```







# plot Sex
```{r gene.expr, cache=FALSE}
df_sex = data.frame(SubID = pb$SubID_cs,
                    rep = pb$rep,
                    batch = pb$batch,
                    UTY = logcounts(pb)["ENSG00000183878_index",], 
                    XIST = logcounts(pb)["ENSG00000229807_index",])

file = "/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze_v2/sex_chr_expr.tsv"
write.table(df_sex, file, sep="\t", quote=FALSE)

ggplot(df_sex, aes(XIST, UTY)) + 
    geom_point() + 
    theme_classic() + 
    theme(aspect.ratio=1)
```



```{r clustering}
library(mclust)

fit = Mclust( data.frame(df_sex$UTY, df_sex$XIST), G=2)

ggplot(df_sex, aes(XIST, UTY, color=fit$z[,1])) + 
    geom_point() + 
    theme_classic() + 
    scale_color_gradient("Male probability", low="red", high="blue") +
    theme(aspect.ratio=1)
```


```{r compare}
df = merge(df_sex[df_sex$rep==1,], df_sex[df_sex$rep==2,], by="SubID")

plot(df$UTY.x, df$UTY.y)
plot(df$XIST.x, df$XIST.y)
```


# At sinle cell level
```{r sc.sex}
# Evaluate pseudobulk on each H5AD
folder = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad-by-donor/"

files = dir(folder, pattern="*.h5ad", full.names=TRUE)

genes = c('ENSG00000183878_index', 'ENSG00000229807_index')

df_sex = lapply(files[1:100], function(file){

  message( match(file, files))

  sce = readH5AD(file, use_hdf5=TRUE)   
  sce <- computeLibraryFactors(sce, assay.type="X")
  sce <- logNormCounts(sce, assay.type="X", pseudo.count=1.01)

  df = data.frame(SubID = sce$SubID_cs,
                  rep   = sce$rep,
                  batch = sce$batch,
                  t(logcounts(sce[genes,])) )

  df
})
df_sex = do.call(rbind, df_sex)

colnames(df_sex)[colnames(df_sex)=='ENSG00000183878_index'] = "XIST"
colnames(df_sex)[colnames(df_sex)=='ENSG00000229807_index'] = "UTY"
```

```{r plots.sex.old, cache=FALSE, eval=FALSE}
# with(df_sex, plot(XIST, UTY))


# fit = Mclust( df_sex[,c("XIST", "UTY")], G=3)

df_known = data.frame(id = c("Male", "Mixed", "Female", "Unknown"),
                      XIST =c(0, 3, 3, 0), 
                      UTY =c(3, 3, 0, 0))

# res = kmeans(df_sex[,c("XIST", "UTY")], centers=df_known[1:3,c("XIST", "UTY")])

# kmeansProbaPost(df_known[1:3,c(2,3)])


# df_pred = predict(fit, df_known[1:3,c(2,3)])
# df_known = df_known[df_pred$classification,]
# beta = do.call(rbind, fit@Means)
# eta = as.matrix(df_known[,c(2,3)]) %*% t(beta)
# apply(eta, 1, which.max)

id_male = which(df_known$id == "Male")

# Continuous
df_known$id[fit@Assignments[,1]]
ggplot(df_sex, aes(XIST, UTY, color=fit$z[,id_male])) + 
    geom_point() + 
    theme_classic() + 
    scale_color_gradient("Male probability", low="red", high="blue", limits=c(0,1)) +
    theme(aspect.ratio=1)

```



```{r sex.gmm}
library(MGMM)

df_known = data.frame(id = c("Male", "Mixed", "Female", "Unknown"),
                      XIST =c(0, 3, 3, 0), 
                      UTY =c(3, 3, 0, 0))

init = as.list(as.data.frame(t(df_known[,c("XIST", "UTY")])))

fit = FitGMM( as.matrix(df_sex[,c("XIST", "UTY")]), k=4, 
  init_mean=init, fix_means=TRUE, eps=1, maxit=10)
```


```{r plot.sex.gmm, cache=FALSE}
col = df_known$id[fit@Assignments[,1]]
ggplot(df_sex, aes(XIST, UTY, color=col)) + 
    geom_point() + 
    theme_classic() + 
    scale_color_brewer("Class assignments", palette="Set1") +
    theme(aspect.ratio=1)
```


