
--
title: "Supervized sex analysis"
subtitle: 'Gene expression of XIST/UTY'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/freeze_v2
ml python git
git pull
R --vanilla
# rm -rf get_sex_expression_v2_cache

system("git pull"); rmarkdown::render("get_sex_expression_v2.Rmd");

# https://hoffmg01.u.hpc.mssm.edu/nps_ad/freeze_v2/get_sex_expression_v2.html

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

```{r load.packages, cache=FALSE}
# Use cache=FALSE so that package are fully loaded each time
# This ensures that forks within mclapply() have these loaded
# Othewise, mclapply() not have access to these libraries and will fail 
#   unless the libraries are manually loaded within each fork
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(dreamlet)
library(scater)
library(tidyverse)

setAutoBlockSize(1e9)
```

```{r read.files}
h5ad_file = "/sc/arion/projects/psychAD/NPS-AD/freeze1_rc/h5ad/211120_NPS-AD_roundMerged_pass2_res20_anno_meta.h5ad"

sce = readH5AD(h5ad_file, use_hdf5=TRUE, raw=TRUE, verbose=TRUE, uns=FALSE)

# normalize gene expression
bpp = SnowParam(8, progressbar=TRUE)
sceSub <- computeLibraryFactors(sce, assay.type="X", BPPARAM=bpp)
sceSub <- logNormCounts(sceSub, assay.type="X", BPPARAM=bpp)
sceSub = sceSub[,!sceSub$pred_dbl]
```




```{r get.genes}
genes = c("XIST", "UTY")

n_chunks = 100

values = seq(1, ncol(sceSub))
idxLst = split(values,      
      cut(seq_along(values),
          n_chunks,
          labels = FALSE))

df = lapply( idxLst, function(idx){
  message(idx[1])
  data.frame(t(assay(sceSub[genes,idx], 'logcounts')))
})
df = do.call(rbind, df)

df$Sex = colData(sceSub)$Sex
df$SubID = droplevels(colData(sceSub)$SubID)
df$Channel = droplevels(colData(sceSub)$Channel)
```

```{r plot0, fig.width=20, fig.height=40}
lvl = levels(df$SubID)[1:10]
ggplot(df[df$SubID %in% lvl,], aes(XIST, UTY, color=Sex)) + 
  geom_point() + 
  theme_classic() +
  theme(aspect.ratio=1) +
  facet_wrap(~SubID, ncol=5)
```

```{r predictor}
fit = glm(Sex ~ XIST*UTY, df, family=binomial())

calcVarPart(fit)

dsgn = data.frame(model.matrix(~ XIST*UTY, df))
df$pred = predict(fit, dsgn, type="response")
```

```{r plot1, fig.width=20, fig.height=80}
ggplot(df[df$SubID %in% lvl,], aes(XIST, UTY, color=pred)) + 
  geom_point() + 
  theme_classic() +
  theme(aspect.ratio=1) + 
  scale_color_gradient(name="Sex prob", high="blue", low="red", limits=c(0,1)) +
  facet_wrap(~SubID, ncol=4)
```

```{r plot2, fig.width=20, fig.height=40}
df[df$SubID %in% lvl,] %>%
  as_tibble %>%
  group_by(Channel) %>%
  summarize( Sex=Sex[1], Predicted.sex = mean(pred))  %>%
  arrange(Sex) %>%
  ggplot(aes(Channel, Predicted.sex, fill=Sex)) + 
    geom_bar(stat="identity") +
    theme_classic() +
    theme(aspect.ratio=10) + 
    scale_fill_manual(name="Labled sex", values=c("red", "blue")) + 
    scale_y_continuous(limits=c(0,1), expand=c(0,0)) +
    coord_flip() 
```


```{r plot3, fig.width=7, fig.height=7}
df %>%
  as_tibble %>%
  group_by(Channel) %>%
  summarize( Sex=Sex[1], Predicted.sex = mean(pred))  %>%
  arrange(Sex) %>%
  ggplot(aes(Sex, Predicted.sex)) + 
    geom_violin(aes(fill=Sex), scale="width") +
    geom_boxplot(width=0.07, fill="grey", outlier.colour='black') +
    theme_classic() +
    theme(aspect.ratio=1) + 
    scale_fill_manual(name="Labled sex", values=c("red", "blue")) + 
    scale_y_continuous(limits=c(0,1), expand=c(0,0)) 
```
























