---
title: "Compare freezes 2.5 and 3"
subtitle: 'Evaluate correlation between expression residuals'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  DATASET: NULL
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/preprocess/
git pull

system("git pull"); rmarkdown::render("compare_freezes.Rmd")


https://hoffmg01.hpc.mssm.edu/PsychAD_analysis/link/freeze2/preprocess/compare_freezes.html


# compare freezes
# 2.5
ls /sc/arion/projects/CommonMind/zengb02/Current_single_cell_eQTL/data/phenotype/*.tsv.gz

# 3
ls /sc/arion/projects/psychAD/NPS-AD/freeze2_rc/residuals/final/*2024-02-01*

--->




```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r read, message=TRUE}
cls = c("EN", "IN", "Astro", "Oligo", "OPC", "Mural", "Endo", "Immune")
cohorts = c("MSSM", "RUSH", "HBCC")

df_grid = expand.grid(class = cls, cohort = cohorts)

library(tidyverse)
library(ggplot2) 

df_cor = lapply(seq(nrow(df_grid)), function(i){

	message(i)

	dir2 = "/sc/arion/projects/CommonMind/zengb02/Current_single_cell_eQTL/data/phenotype/"	
	pat = paste0(df_grid$cohort[i], ".*_residualsPearson_SubID_class_", df_grid$class[i], ".tsv.gz")
	file2 = dir(dir2, pattern=pat, full.names=TRUE)
	file2 = file2[length(file2)]

	dir3 = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/residuals/final/"
	pat = paste0(df_grid$cohort[i], "_2024-02-01.*_residualsPearson_SubID_class_", df_grid$class[i], ".tsv.gz")	
	file3 = dir(dir3, pattern=pat, full.names=TRUE)

	df2 = read.table(file2, header=TRUE) %>% t
	df3 = read.table(file3, header=TRUE) %>% t

	ids = intersect(rownames(df2), rownames(df3))
	df2 = df2[ids,]
	df3 = df3[ids,]

	genes = intersect(colnames(df2), colnames(df3))

	df_cor = lapply(genes, function(g){
		data.frame(Cohort = df_grid$cohort[i], 
						CellType = df_grid$class[i], 
						gene = g, 
						cor = cor(df2[,g], df3[,g]))
	})
	bind_rows(df_cor)
})
df_cor = bind_rows(df_cor)
```

```{r plot, cache=FALSE}
ggplot(df_cor, aes(CellType, cor, fill=CellType)) +
	geom_violin() +
	theme_classic() +
	theme(aspect.ratio = 1, 
		legend.position="none", 
		axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
		plot.title = element_text(hjust = 0.5)) +
	ylab("Correlation") +
	ggtitle("residualsPearson class") +
	scale_y_continuous(limits=c(0, 1), expand=c(0,0)) +
	facet_wrap(~Cohort)
```




