---
title: "Preprocess H5AD files"
subtitle: 'Save pseudobulk, etc'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  DATASET: NULL
---


<!--- 

cd /sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/analysis/freeze2/preprocess/
ml python git pandoc
git pull origin master
R --vanilla

# system("git pull origin master"); rmarkdown::render("preprocess.Rmd");


library(rmarkdown)
library(tidyverse)

h5ad_files = c(
RUSH = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/RUSH_2023-02-07_14_21.h5ad", 
HBCC = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/HBCC_2023-02-07_14_53.h5ad",
# MSSM = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/",
# FULL = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/",
AGING = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/AGING_2023-02-07_18_16.h5ad")

run = function(){
system("git pull origin master");

names(h5ad_files)[1] %>% 
  walk(function(x) render("preprocess.Rmd",
          params = list(DATASET = h5ad_files[x]),
          output_file = paste0("./preprocess_", x, ".html")))
}




# https://hoffmg01.hpc.mssm.edu/nps_ad/analysis/freeze2/preprocess/

--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

 <font size="5">__Evaluating dataset: `r names(params$DATASET)`__</font>


# Loading
## Libraries
```{r load.packages, cache=FALSE}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(zellkonverter)
library(dreamlet)
library(zenith)
library(DelayedArray)
library(GSEABase)
library(scater)
library(tidyverse)
library(ggplot2)
library(cowplot) 
library(org.Hs.eg.db)
})

# update block size for reading h5ad file from disk
setAutoBlockSize(1e9)
```

## H5AD
```{r load.data}
sce = readH5AD(params$DATASET, use_hdf5=TRUE, verbose=TRUE)
assayNames(sce)[1] = "counts"

# order of cell types used for plotting
ctorder = c('EN_L2_3_IT', 'EN_L3_5_IT_1', 'EN_L3_5_IT_2', 'EN_L3_5_IT_3', 'EN_L5_IT', 'EN_L5_6_NP', 'EN_L6_CT', 'EN_L6_IT', 'EN_NF', 'IN_ADARB2', 'IN_LAMP5', 'IN_PVALB', 'IN_PVALB_CHC', 'IN_SST', 'IN_VIP', 'Oligo', 'OPC', 'Astro', 'Micro_PVM', 'CD8_T', 'PC', 'VLMC','Endo', "Immune")
```


# Compute pseudobulk at multiple levels
```{r combineData, message=TRUE}
# Create pseudo-bulk SingleCellExperiment
for(cluster_id in c("class", "subclass", "subtype") ){
  for(sample_id in c("Channel", "SubID") ){
    # Compute pseudobulk
    pb = aggregateToPseudoBulk(sce[, 1:10000],
      assay = "counts", 
      cluster_id = cluster_id,
      sample_id = sample_id,
      BPPARAM = SnowParam(1))

    filePrefix = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/", gsub(".h5ad$", "", basename(params$DATASET)), "_PB_", sample_id, "_", cluster_id)

    # Save as RDS
    saveRDS(pb, file = paste0(filePrefix, ".RDS"))

    # Save as H5AD
    writeH5AD( pb, file = paste0(filePrefix, ".h5ad"), compression = "lzf" )
  }
}
```

# Summarizing data
## UMAP
```{r umap}
plotProjection(sce, "X_umap", "subclass", order=ctorder)  + ggtitle("subclass")
```


## Summarize cell counts
```{r summarize.cell.counts, fig.width=5}
# cells per Channel
colData(sce)$Channel %>% 
  table %>% 
  hist(main=paste0("Cell counts per Channel: mean=", format(mean(.), digits=2), ", median = ", format(median(.), digits=2)))

colData(sce)$SubID %>% 
  table %>% 
  hist(main=paste0("Cell counts per SubID: mean=", format(mean(.), digits=2), ", median = ", format(median(.), digits=2)))

# Number of cells observed per Channel
colData(sce) %>%
  xtabs( ~ Channel + subclass,.) %>%
  as_tibble %>%
  pivot_longer(cols=Channel) %>%
  mutate(subclass = factor(subclass, ctorder)) %>%  
  ggplot(aes(subclass, n, fill=subclass)) + 
    geom_violin(color = NA) + 
    geom_boxplot(width=.1, outlier.size=.1) +
    theme_classic() + 
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5),
      legend.position="none") + 
    scale_y_log10() +
    coord_flip() +
    ylab("Number of cells observed per Channel") +
    xlab('')

# Number of cells observed per Subject
fig.cells_subject = colData(sce) %>%
  xtabs( ~ SubID + subclass,.) %>%
  as_tibble %>%
  pivot_longer(cols=SubID) %>%
  mutate(subclass = factor(subclass, ctorder)) %>%  
  ggplot(aes(subclass, n, fill=subclass)) + 
    geom_violin(color = NA) + 
    geom_boxplot(width=.1, outlier.size=.1) +
    theme_classic() + 
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5),
      legend.position="none") + 
    scale_y_log10() +
    coord_flip() +
    ylab("Number of cells observed per Subject") +
    xlab('')
fig.cells_subject    
```

```{r read.pseudobulk}
filePrefix = paste0("/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/", gsub(".h5ad$", "", basename(params$DATASET)), "_PB_", "Channel", "_", "subclass")

# Read from RDS
pb = readRDS(paste0(filePrefix, ".RDS"))
```

## Summarize read counts
```{r summarize.read.counts}
# extract read counts for each Channel
df_counts = lapply( assayNames(pb), function(x){
  data = assay(pb, x)

  data.frame(celltype = x, ID = colnames(data), readCounts = colSums(data))
})
df_counts = do.call(rbind, df_counts)
df_counts$celltype = factor(df_counts$celltype, ctorder)  

ggplot(df_counts, aes(celltype, readCounts, fill=celltype)) +  
    geom_violin(color = NA) + 
    geom_boxplot(width=.1, outlier.size=.1) +
    theme_classic() + 
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5),
      legend.position="none") + 
    scale_y_log10() +
    coord_flip() +
    ylab("Number of reads observed for each Channel") +
    xlab('') +
    ggtitle('Reads per cell cluster for each Channel')

# extract cell counts
df_rate = cellCounts(pb) %>%
            as.data.frame %>%
            mutate(ID = rownames(.))  %>% 
            pivot_longer(cols=-ID, values_to="ncells", names_to="celltype") %>%
            mutate(celltype = factor(celltype, ctorder))  

# plot reads per cell
inner_join(df_counts, df_rate, by=c("celltype", "ID")) %>%
  ggplot(aes(celltype, readCounts/ncells, fill=celltype)) +  
    geom_violin(color = NA) + 
    geom_boxplot(width=.1, outlier.size=.1) +
    theme_classic() + 
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5),
      legend.position="none") + 
    scale_y_log10() +
    coord_flip() +
    ylab('Reads per cell') +
    xlab('') +
    ggtitle('Reads per cell for each Channel')
```


## Cell type specificity
```{r cellTypeSpecificity}
df_cellScore = cellTypeSpecificity( pb )
 
plotViolin(df_cellScore, assays=ctorder)  
```


### Show cell markers
```{r cellMarkers}
genes = c('RBFOX3', 'MEG3', 'SLC17A7',
'RBFOX3', 'MEG3', 'GAD1', 'GAD2', 'GRIK1',
'SST',
'PVALB',
'VIP',
'SLC1A3', 'GFAP', 'APOE', 'SLC1A2', 'SLC14A1',
'PLP1', 'MAG', 'MBP',
'PDGFRA', 'VCAN',
'FLT1', 'CLDN5',
'PDGFRB',
'TGFBR1', 'DOCK8', 'CD74', 'CSF1R', 'MS4A6A', 'PLXDC2')
 
df_genes = AnnotationDbi::select(org.Hs.eg.db, genes, "ENSEMBL", "SYMBOL")

df_sub = df_cellScore[rownames(df_cellScore) %in% df_genes$ENSEMBL,]
idx = match(rownames(df_sub), df_genes$ENSEMBL)
rownames(df_sub) = df_genes$SYMBOL[idx]

plotPercentBars(df_cellScore, genes=unique(genes), assays=ctorder)  
```

```{r heatmap, fig.height=7, fig.width=7}
dreamlet::plotHeatmap(df, genes=unique(genes), assays=ctorder)  
```


# Process data: log2 CPM + voom precision weights
```{r voom}
# Normalize and apply voom
form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age)
form = ~ 1

res.proc = processAssays( pb, form, BPPARAM = SnowParam(12))
```

```{r voom.plot, fig.height=15, fig.width=10, cache=TRUE}
plotVoom( res.proc, ncol=4, assays=ctorder ) + theme_classic()  
```


# Variance Partitioning Analysis
```{r varPart}
# form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age)
form = ~ scale(Age) 

res.vp = fitVarPart(res.proc, form, BPPARAM = SnowParam(12))
```



```{r vp.plot, fig.height=15, fig.width=10}
plotVarPart( sortCols(res.vp), label.angle=45, ncol=4, assays=ctorder )  
```



# Correlation with and between donors
```{r within_btw, fig.height=10, fig.width=10}
source("/sc/arion/projects/CommonMind/hoffman/NPS-AD/work/nps_ad/common_analyses.R")
 
fig = eval_within_across_donor( res.proc, "SubID" )

fig + theme(panel.grid.minor = element_blank(),
            panel.grid.minor.y = element_blank())
```
